// ─── Supplier Master — Seed Data ─────────────────────────────────────────────

import type { BusinessPartner } from '../types/supplierMaster.types';

export const SEED_SUPPLIERS: BusinessPartner[] = [
  {
    id: 'BP-0001',
    bpCode: 'BP-0001',
    bpLegalName: 'Apex Auto Components Pvt. Ltd.',
    bpType: 'Supplier',
    marketingName: 'Apex Auto',
    displayName: 'Apex Auto Components',
    bpCategory: 'Manufacturer',
    countryOfRegistration: 'India',
    businessType: 'Private Limited',
    industryType: 'Automotive',
    noOfEmployees: '201–500',
    foundingDate: '2008-03-15',
    websiteUrl: 'https://apexauto.in',
    annualTurnover: '12,00,00,000',
    annualRevenue: '11,50,00,000',
    financialYear: '2024–25',
    financialCurrency: 'INR',
    status: 'Active',
    effectiveFromDate: '2024-04-01',
    effectiveToDate: '',
    description: 'Premium manufacturer of automotive filters, brake pads, and engine components.',
    contacts: [
      {
        id: 'BPCT-0001',
        contactType: 'Primary',
        contactName: 'Rajesh Mehta',
        department: 'Sales',
        designation: 'Regional Sales Manager',
        countryCode: '+91',
        phone: '9876543210',
        email: 'rajesh.mehta@apexauto.in',
        fax: '',
        status: 'Active',
      },
      {
        id: 'BPCT-0002',
        contactType: 'Accounts',
        contactName: 'Priya Sharma',
        department: 'Finance',
        designation: 'Accounts Executive',
        countryCode: '+91',
        phone: '9123456780',
        email: 'priya.sharma@apexauto.in',
        fax: '0222345678',
        status: 'Active',
      },
    ],
    addresses: [
      {
        id: 'BPAD-0001',
        addressType: 'Registered',
        addressLine1: '301, Industrial Estate',
        addressLine2: 'Andheri East',
        country: 'India',
        state: 'Maharashtra',
        city: 'Mumbai',
        pin: '400069',
        latitude: '19.1136',
        longitude: '72.8697',
        isDefault: true,
        status: 'Active',
      },
      {
        id: 'BPAD-0002',
        addressType: 'Warehouse',
        addressLine1: 'Plot 45, MIDC Phase II',
        addressLine2: '',
        country: 'India',
        state: 'Maharashtra',
        city: 'Pune',
        pin: '411018',
        latitude: '',
        longitude: '',
        isDefault: false,
        status: 'Active',
      },
    ],
    orgMappings: [
      {
        id: 'BPOM-0001',
        applyToAll: false,
        organisationId: 'ORG-001',
        organisationName: 'HQ — Head Office',
        effectiveDate: '2024-04-01',
        expirationDate: '',
        status: 'Active',
      },
      {
        id: 'BPOM-0002',
        applyToAll: false,
        organisationId: 'ORG-002',
        organisationName: 'Region North',
        effectiveDate: '2024-04-01',
        expirationDate: '',
        status: 'Active',
      },
    ],
    taxRegistered: true,
    taxJurisdiction: 'India — GST',
    complianceDocuments: [
      {
        id: 'BPCD-0001',
        documentType: 'GST Certificate',
        documentNumber: '27AAPCA1234B1Z5',
        issueDate: '2023-07-01',
        expiryDate: '',
        allowTransactionAfterExpiry: false,
        attachmentName: 'gst_certificate_apex.pdf',
        status: 'Active',
      },
      {
        id: 'BPCD-0002',
        documentType: 'PAN Card',
        documentNumber: 'AAPCA1234B',
        issueDate: '2008-03-20',
        expiryDate: '',
        allowTransactionAfterExpiry: false,
        attachmentName: 'pan_apex.pdf',
        status: 'Active',
      },
    ],
    bankDetails: [
      {
        id: 'BPBK-0001',
        bankCode: 'HDFC0001234',
        bankName: 'HDFC Bank',
        branchName: 'Andheri East',
        accountHolderName: 'Apex Auto Components Pvt Ltd',
        accountNumber: '50200012345678',
        accountType: 'Current',
        defaultCurrency: 'INR',
        isDefaultAccount: true,
        status: 'Active',
        bankAddress: {
          addressLine1: 'Shop 12, Saki Vihar Rd',
          addressLine2: '',
          country: 'India',
          state: 'Maharashtra',
          city: 'Mumbai',
          pin: '400072',
        },
      },
    ],
    paymentTerms: {
      advanceAllowed: false,
      advancePercentage: 0,
      settlementType: 'Full Settlement',
      paymentMode: 'NEFT',
      creditDays: 30,
      creditLimit: 5000000,
      creditLimitCurrency: 'INR',
    },
    itemMappings: [
      {
        id: 'BPIM-0001',
        itemCode: 'ITM-001',
        itemName: 'Engine Oil Filter',
        orderUom: 'Each',
        minOrderQty: 100,
        maxQtyScope: 'Per Order',
        maxOrderQty: 5000,
        orderMultiple: 50,
        stdLeadTimeDays: 7,
        minLeadTimeDays: 5,
        maxLeadTimeDays: 14,
        isReturnable: true,
        returnPeriodDays: 30,
        effectiveFromDate: '2024-04-01',
        effectiveToDate: '',
        status: 'Active',
      },
      {
        id: 'BPIM-0002',
        itemCode: 'ITM-002',
        itemName: 'Brake Pad Assembly',
        orderUom: 'Set',
        minOrderQty: 50,
        maxQtyScope: 'Per Order',
        maxOrderQty: 2000,
        orderMultiple: 25,
        stdLeadTimeDays: 10,
        minLeadTimeDays: 7,
        maxLeadTimeDays: 21,
        isReturnable: false,
        returnPeriodDays: 0,
        effectiveFromDate: '2024-04-01',
        effectiveToDate: '',
        status: 'Active',
      },
    ],
    createdAt: '2024-04-01T09:00:00.000Z',
    updatedAt: '2025-01-10T14:30:00.000Z',
  },
  {
    id: 'BP-0002',
    bpCode: 'BP-0002',
    bpLegalName: 'Swift Logistics Solutions LLP',
    bpType: 'Transporter',
    marketingName: 'Swift Logistics',
    displayName: 'Swift Logistics',
    bpCategory: 'Service Provider',
    countryOfRegistration: 'India',
    businessType: 'LLP',
    industryType: 'Logistics',
    noOfEmployees: '51–200',
    foundingDate: '2015-08-10',
    websiteUrl: 'https://swiftlogistics.co.in',
    annualTurnover: '3,50,00,000',
    annualRevenue: '3,20,00,000',
    financialYear: '2024–25',
    financialCurrency: 'INR',
    status: 'Active',
    effectiveFromDate: '2024-06-01',
    effectiveToDate: '',
    description: 'Pan-India logistics and last-mile delivery partner.',
    contacts: [
      {
        id: 'BPCT-0003',
        contactType: 'Primary',
        contactName: 'Arvind Kumar',
        department: 'Operations',
        designation: 'Operations Head',
        countryCode: '+91',
        phone: '9988776655',
        email: 'arvind@swiftlogistics.co.in',
        fax: '',
        status: 'Active',
      },
    ],
    addresses: [
      {
        id: 'BPAD-0003',
        addressType: 'Registered',
        addressLine1: '14/2, Transport Nagar',
        addressLine2: '',
        country: 'India',
        state: 'Delhi',
        city: 'New Delhi',
        pin: '110041',
        latitude: '',
        longitude: '',
        isDefault: true,
        status: 'Active',
      },
    ],
    orgMappings: [
      {
        id: 'BPOM-0003',
        applyToAll: true,
        organisationId: '',
        organisationName: '',
        effectiveDate: '2024-06-01',
        expirationDate: '',
        status: 'Active',
      },
    ],
    taxRegistered: true,
    taxJurisdiction: 'India — GST',
    complianceDocuments: [
      {
        id: 'BPCD-0003',
        documentType: 'GST Certificate',
        documentNumber: '07AABFS1234C1Z1',
        issueDate: '2023-07-01',
        expiryDate: '',
        allowTransactionAfterExpiry: false,
        attachmentName: '',
        status: 'Active',
      },
    ],
    bankDetails: [
      {
        id: 'BPBK-0002',
        bankCode: 'ICIC0002345',
        bankName: 'ICICI Bank',
        branchName: 'Connaught Place',
        accountHolderName: 'Swift Logistics Solutions LLP',
        accountNumber: '001201234567',
        accountType: 'Current',
        defaultCurrency: 'INR',
        isDefaultAccount: true,
        status: 'Active',
        bankAddress: {
          addressLine1: 'Block G, Connaught Place',
          addressLine2: '',
          country: 'India',
          state: 'Delhi',
          city: 'New Delhi',
          pin: '110001',
        },
      },
    ],
    paymentTerms: {
      advanceAllowed: false,
      advancePercentage: 0,
      settlementType: 'Running Account',
      paymentMode: 'NEFT',
      creditDays: 15,
      creditLimit: 1000000,
      creditLimitCurrency: 'INR',
    },
    itemMappings: [],
    createdAt: '2024-06-01T10:00:00.000Z',
    updatedAt: '2024-11-20T11:00:00.000Z',
  },
  {
    id: 'BP-0003',
    bpCode: 'BP-0003',
    bpLegalName: 'Bharat Finance Corporation Ltd.',
    bpType: 'Financier',
    marketingName: 'Bharat Finance',
    displayName: 'Bharat Finance Corp',
    bpCategory: 'Service Provider',
    countryOfRegistration: 'India',
    businessType: 'Public Limited',
    industryType: 'Financial Services',
    noOfEmployees: '1001–5000',
    foundingDate: '2001-01-05',
    websiteUrl: 'https://bharatfinance.co.in',
    annualTurnover: '',
    annualRevenue: '',
    financialYear: '2024–25',
    financialCurrency: 'INR',
    status: 'Active',
    effectiveFromDate: '2023-01-01',
    effectiveToDate: '',
    description: 'NBFC providing vehicle and equipment financing to dealers and end customers.',
    contacts: [
      {
        id: 'BPCT-0004',
        contactType: 'Primary',
        contactName: 'Neha Joshi',
        department: 'Partnerships',
        designation: 'Relationship Manager',
        countryCode: '+91',
        phone: '9001234567',
        email: 'neha.joshi@bharatfinance.co.in',
        fax: '',
        status: 'Active',
      },
    ],
    addresses: [
      {
        id: 'BPAD-0004',
        addressType: 'Corporate',
        addressLine1: 'Tower B, BKC Complex',
        addressLine2: 'Bandra Kurla Complex',
        country: 'India',
        state: 'Maharashtra',
        city: 'Mumbai',
        pin: '400051',
        latitude: '',
        longitude: '',
        isDefault: true,
        status: 'Active',
      },
    ],
    orgMappings: [],
    taxRegistered: true,
    taxJurisdiction: 'India — GST',
    complianceDocuments: [
      {
        id: 'BPCD-0004',
        documentType: 'GST Certificate',
        documentNumber: '27AABCB5678D1Z3',
        issueDate: '2022-04-01',
        expiryDate: '',
        allowTransactionAfterExpiry: false,
        attachmentName: '',
        status: 'Active',
      },
    ],
    bankDetails: [
      {
        id: 'BPBK-0003',
        bankCode: 'AXIS0003456',
        bankName: 'Axis Bank',
        branchName: 'BKC Branch',
        accountHolderName: 'Bharat Finance Corporation Ltd',
        accountNumber: '92009112345678',
        accountType: 'Current',
        defaultCurrency: 'INR',
        isDefaultAccount: true,
        status: 'Active',
        bankAddress: {
          addressLine1: 'Ground Floor, Tower A, BKC',
          addressLine2: '',
          country: 'India',
          state: 'Maharashtra',
          city: 'Mumbai',
          pin: '400051',
        },
      },
    ],
    paymentTerms: {
      advanceAllowed: false,
      advancePercentage: 0,
      settlementType: 'Full Settlement',
      paymentMode: 'RTGS',
      creditDays: 0,
      creditLimit: 0,
      creditLimitCurrency: 'INR',
    },
    itemMappings: [],
    createdAt: '2023-01-01T08:00:00.000Z',
    updatedAt: '2025-02-15T09:00:00.000Z',
  },
  {
    id: 'BP-0004',
    bpCode: 'BP-0004',
    bpLegalName: 'Global Parts Distributors Pvt. Ltd.',
    bpType: 'Supplier',
    marketingName: 'Global Parts',
    displayName: 'Global Parts Distributors',
    bpCategory: 'Distributor',
    countryOfRegistration: 'India',
    businessType: 'Private Limited',
    industryType: 'Automotive',
    noOfEmployees: '51–200',
    foundingDate: '2012-06-20',
    websiteUrl: '',
    annualTurnover: '5,00,00,000',
    annualRevenue: '4,70,00,000',
    financialYear: '2024–25',
    financialCurrency: 'INR',
    status: 'Draft',
    effectiveFromDate: '',
    effectiveToDate: '',
    description: 'Distributor of OEM and aftermarket spare parts for passenger and commercial vehicles.',
    contacts: [],
    addresses: [
      {
        id: 'BPAD-0005',
        addressType: 'Registered',
        addressLine1: '22, Auto Parts Market',
        addressLine2: 'Kirti Nagar',
        country: 'India',
        state: 'Delhi',
        city: 'New Delhi',
        pin: '110015',
        latitude: '',
        longitude: '',
        isDefault: true,
        status: 'Active',
      },
    ],
    orgMappings: [],
    taxRegistered: false,
    taxJurisdiction: '',
    complianceDocuments: [],
    bankDetails: [],
    paymentTerms: {
      advanceAllowed: true,
      advancePercentage: 20,
      settlementType: 'Partial Settlement',
      paymentMode: 'Cheque',
      creditDays: 45,
      creditLimit: 2000000,
      creditLimitCurrency: 'INR',
    },
    itemMappings: [
      {
        id: 'BPIM-0003',
        itemCode: 'ITM-003',
        itemName: 'Air Filter Element',
        orderUom: 'Each',
        minOrderQty: 200,
        maxQtyScope: 'Per Month',
        maxOrderQty: 10000,
        orderMultiple: 100,
        stdLeadTimeDays: 5,
        minLeadTimeDays: 3,
        maxLeadTimeDays: 10,
        isReturnable: true,
        returnPeriodDays: 15,
        effectiveFromDate: '',
        effectiveToDate: '',
        status: 'Active',
      },
    ],
    createdAt: '2025-05-01T07:00:00.000Z',
    updatedAt: '2025-05-01T07:00:00.000Z',
  },
];
