import { lazy } from 'react';

export const BusinessSettings = lazy(() => import('../BusinessSettings'));
export const CreateDelivery = lazy(() => import('../pages/delivery/CreateDelivery'));
export const CreatePurchaseInvoice = lazy(() => import('../pages/purchase-invoice/CreatePurchaseInvoice'));
export const CreatePurchaseOrder = lazy(() => import('../pages/purchase-order/CreatePurchaseOrder'));
export const CreatePurchaseReceipt = lazy(() => import('../pages/purchase-receipt/CreatePurchaseReceipt'));
export const CreatePurchaseRequisition = lazy(() => import('../pages/purchase-requisition/CreatePurchaseRequisition'));
export const CreateSaleAllocation = lazy(() => import('../pages/sale-allocation/CreateSaleAllocation'));
export const CreateSaleAllocationRequisition = lazy(() => import('../pages/sale-allocation-requisition/CreateSaleAllocationRequisition'));
export const CreateSaleInvoice = lazy(() => import('../pages/sale-invoice/CreateSaleInvoice'));
export const CreateSaleOrder = lazy(() => import('../pages/sale-order/CreateSaleOrder'));
export const DeliveryList = lazy(() => import('../pages/delivery/deliverylist'));
export const ExcellonBrandGuidelinesPreview = lazy(() => import('../ExcellonBrandGuidelinesPreview'));
export const FormLayoutEditor = lazy(() => import('../FormLayoutEditor'));
export const FormLayoutSettings = lazy(() => import('../FormLayoutSettings'));
export const PurchaseInvoiceList = lazy(() => import('../pages/purchase-invoice/purchaseinvoicelist'));
export const PurchaseReceiptList = lazy(() => import('../pages/purchase-receipt/purchasereceiptlist'));
export const PurchaseRequisitionCatalogueView = lazy(() => import('../pages/purchase-requisition/PurchaseRequisitionCatalogueView'));
export const PurchaseOrderList = lazy(() => import('../pages/purchase-order/purhcaseorderlist'));
export const SaleAllocationList = lazy(() => import('../pages/sale-allocation/saleallocationlist'));
export const SaleAllocationRequisitionList = lazy(() => import('../pages/sale-allocation-requisition/saleallocationrequisitionlist'));
export const SaleInvoiceList = lazy(() => import('../pages/sale-invoice/saleinvoicelist'));
export const SaleOrderList = lazy(() => import('../pages/sale-order/saleorderlist'));