import { lazy } from 'react';

export const BusinessSettings = lazy(() => import('../BusinessSettings'));
export const CreateDelivery = lazy(() => import('../delivery/CreateDelivery'));
export const CreatePurchaseInvoice = lazy(() => import('../purchase invoice/CreatePurchaseInvoice'));
export const CreatePurchaseOrder = lazy(() => import('../purchase order/CreatePurchaseOrder'));
export const CreatePurchaseReceipt = lazy(() => import('../purhcase receipt/CreatePurchaseReceipt'));
export const CreatePurchaseRequisition = lazy(() => import('../purchase requisition/CreatePurchaseRequisition'));
export const CreateSaleAllocation = lazy(() => import('../sale allocation/CreateSaleAllocation'));
export const CreateSaleAllocationRequisition = lazy(() => import('../sale allocation requisition/CreateSaleAllocationRequisition'));
export const CreateSaleInvoice = lazy(() => import('../sale invoice/CreateSaleInvoice'));
export const CreateSaleOrder = lazy(() => import('../sale order/CreateSaleOrder'));
export const DeliveryList = lazy(() => import('../delivery/deliverylist'));
export const ExcellonBrandGuidelinesPreview = lazy(() => import('../ExcellonBrandGuidelinesPreview'));
export const FormLayoutEditor = lazy(() => import('../FormLayoutEditor'));
export const FormLayoutSettings = lazy(() => import('../FormLayoutSettings'));
export const PurchaseInvoiceList = lazy(() => import('../purchase invoice/purchaseinvoicelist'));
export const PurchaseReceiptList = lazy(() => import('../purhcase receipt/purchasereceiptlist'));
export const PurchaseRequisitionCatalogueView = lazy(() => import('../purchase requisition/PurchaseRequisitionCatalogueView'));
export const PurhcaseOrderList = lazy(() => import('../purchase order/purhcaseorderlist'));
export const SaleAllocationList = lazy(() => import('../sale allocation/saleallocationlist'));
export const SaleAllocationRequisitionList = lazy(() => import('../sale allocation requisition/saleallocationrequisitionlist'));
export const SaleInvoiceList = lazy(() => import('../sale invoice/saleinvoicelist'));
export const SaleOrderList = lazy(() => import('../sale order/saleorderlist'));