import type { CommandItem } from './navigationTypes';

export const commandRegistry: CommandItem[] = [
  // ─── Navigate: Core admin pages ──────────────────────────────────────────
  {
    id: 'open-admin-dashboard',
    label: 'Open Admin Dashboard',
    description: 'Go to the admin overview and setup assistant.',
    actionType: 'navigate',
    path: '/admin',
    keywords: ['admin', 'dashboard', 'home', 'overview', 'setup', 'start', 'configuration'],
  },
  {
    id: 'open-organisation-master',
    label: 'Open Organisation Master',
    description: 'Configure legal entity, branches, tax identifiers, and branding.',
    actionType: 'navigate',
    path: '/admin/master/organisation-master',
    keywords: ['organisation', 'company', 'entity', 'branch', 'tax', 'legal', 'gst', 'pan', 'logo', 'address'],
  },
  {
    id: 'open-kyc-setup',
    label: 'Open KYC Setup',
    description: 'Configure KYC proof requirements and document verification rules.',
    actionType: 'navigate',
    path: '/admin/master/kyc-setup',
    keywords: ['kyc', 'verification', 'identity', 'document', 'proof', 'passport', 'aadhaar', 'onboarding'],
  },
  {
    id: 'open-picklist-master',
    label: 'Open Picklist Master',
    description: 'Manage dropdown options, enumerations, and dependent list values.',
    actionType: 'navigate',
    path: '/admin/master/picklist-master',
    keywords: ['picklist', 'dropdown', 'enum', 'values', 'options', 'list', 'dependent', 'select'],
  },
  {
    id: 'open-numbering-code-setup',
    label: 'Open Numbering & Code Setup',
    description: 'Configure document numbering sequences, prefixes, and reset rules.',
    actionType: 'navigate',
    path: '/admin/master/numbering-code-setup',
    keywords: ['numbering', 'code', 'sequence', 'prefix', 'format', 'serial', 'invoice', 'order', 'auto'],
  },
  {
    id: 'open-code-generation-policy',
    label: 'Open Code Generation Policy',
    description: 'Define policies for automatic code and ID generation per entity.',
    actionType: 'navigate',
    path: '/admin/master/code-generation-policy',
    keywords: ['code generation', 'policy', 'auto', 'id', 'rules', 'series', 'padding', 'reset', 'prefix'],
  },
  {
    id: 'browse-admin-masters',
    label: 'Browse All Admin Masters',
    description: 'Search and navigate to any admin configuration master.',
    actionType: 'navigate',
    path: '/admin',
    keywords: ['search', 'browse', 'find', 'all', 'masters', 'list', 'admin', 'configure', 'explore'],
  },

  // ─── Navigate: Other useful shortcuts ────────────────────────────────────
  {
    id: 'open-user-master',
    label: 'Open User Master',
    description: 'Create and manage system user accounts and access.',
    actionType: 'navigate',
    path: '/admin/master/user-master',
    keywords: ['user', 'account', 'access', 'login', 'staff', 'employee'],
  },
  {
    id: 'open-role-master',
    label: 'Open Role Master',
    description: 'Define user roles and access control levels.',
    actionType: 'navigate',
    path: '/admin/master/role-master',
    keywords: ['role', 'permission', 'access', 'rbac', 'security', 'rights'],
  },

  // ─── Help ─────────────────────────────────────────────────────────────────
  {
    id: 'help-admin',
    label: 'Open Admin Help',
    description: 'Open the help guide for admin setup and configuration.',
    actionType: 'open-help',
    helpTopicId: 'admin-dashboard',
    keywords: ['help', 'guide', 'admin', 'setup', 'how', 'docs', 'documentation'],
  },
  {
    id: 'help-organisation',
    label: 'Help: Organisation Master',
    description: 'Step-by-step guide for configuring your legal entity and branches.',
    actionType: 'open-help',
    helpTopicId: 'organisation-master',
    keywords: ['help', 'organisation', 'company', 'entity', 'guide', 'branch'],
  },
  {
    id: 'help-numbering',
    label: 'Help: Numbering & Code Setup',
    description: 'Understand prefixes, series types, and reset frequency.',
    actionType: 'open-help',
    helpTopicId: 'numbering-code-setup',
    keywords: ['help', 'numbering', 'prefix', 'series', 'code', 'guide', 'sequence'],
  },
  {
    id: 'help-kyc',
    label: 'Help: KYC Setup',
    description: 'Configure entity proof rules and document validation.',
    actionType: 'open-help',
    helpTopicId: 'kyc-setup',
    keywords: ['help', 'kyc', 'proof', 'document', 'validation', 'guide', 'onboarding'],
  },
  {
    id: 'help-picklist',
    label: 'Help: Picklist Master',
    description: 'Create simple, dependent, and multi-level dropdown lists.',
    actionType: 'open-help',
    helpTopicId: 'picklist-master',
    keywords: ['help', 'picklist', 'dropdown', 'dependent', 'list', 'guide', 'values'],
  },
  {
    id: 'help-code-generation',
    label: 'Help: Code Generation Policy',
    description: 'Learn how code policies combine prefix, series, and reset rules.',
    actionType: 'open-help',
    helpTopicId: 'code-generation-policy',
    keywords: ['help', 'code generation', 'policy', 'prefix', 'guide', 'auto'],
  },
];
