// Seed data for all 21 Sale Order rule sets — derived from blueprint Section 7.
// These are TypeScript reference types for backend seeding only.
// The app does NOT load these at runtime.

import type { RuleSetConfig } from '../types/configuration';

export const SALE_ORDER_RULE_SET_SEED: RuleSetConfig[] = [
  {
    ruleSetCode: 'SO_PRE_VALIDATION_RULES',
    ruleSetName: 'Sale Order Pre Validation',
    entityName: 'SaleOrder',
    description: 'Initial checks before any processing begins.',
    version: 1,
    isActive: true,
    rules: [
      { ruleCode: 'SO-PRE-DOC-TYPE-VALID', field: 'DocumentType', ruleType: 'Validation', action: 'RaiseError', owner: 'RuleEngine', isActive: true, order: 10 },
      { ruleCode: 'SO-PRE-ENTITY-CONTEXT-REQ', field: 'EntityContext', ruleType: 'Validation', action: 'RaiseError', owner: 'RuleEngine', isActive: true, order: 20 },
      { ruleCode: 'SO-PRE-TENANT-REQ', field: 'TenantId', ruleType: 'Validation', action: 'RaiseError', owner: 'RuleEngine', isActive: true, order: 30 },
    ],
  },
  {
    ruleSetCode: 'SO_HEADER_VALIDATION_RULES',
    ruleSetName: 'Sale Order Header Validation',
    entityName: 'SaleOrder',
    description: 'Validates all header-level mandatory and conditional fields.',
    version: 1,
    isActive: true,
    rules: [
      { ruleCode: 'SO-HDR-DOC-DATE-REQ', field: 'DocumentDate', ruleType: 'Validation', action: 'RaiseError', owner: 'RuleEngine', isActive: true, order: 10 },
      { ruleCode: 'SO-HDR-DOC-DATE-OPEN-PERIOD', field: 'DocumentDate', ruleType: 'Validation', action: 'RaiseError', owner: 'RuleEngine', isActive: true, order: 20 },
      { ruleCode: 'SO-HDR-ORG-REQ', field: 'Organisation', ruleType: 'Validation', action: 'RaiseError', owner: 'RuleEngine', isActive: true, order: 30 },
      { ruleCode: 'SO-HDR-BRANCH-REQ', field: 'Branch', ruleType: 'Validation', action: 'RaiseError', owner: 'RuleEngine', isActive: true, order: 40 },
      { ruleCode: 'SO-HDR-DEPT-BRANCH-MATCH', field: 'Department', ruleType: 'ConditionalValidation', action: 'RaiseError', owner: 'RuleEngine', isActive: true, order: 50 },
      { ruleCode: 'SO-HDR-CUSTOMER-REQ', field: 'Customer', ruleType: 'Validation', action: 'RaiseError', owner: 'RuleEngine', isActive: true, order: 60 },
      { ruleCode: 'SO-HDR-SALES-OWNER-REQ', field: 'SalesOwner', ruleType: 'Validation', action: 'RaiseError', owner: 'RuleEngine', isActive: true, order: 70 },
      { ruleCode: 'SO-HDR-SALES-OWNER-ACTIVE', field: 'SalesOwner', ruleType: 'Validation', action: 'RaiseError', owner: 'RuleEngine', isActive: true, order: 80 },
      { ruleCode: 'SO-HDR-TAX-JURISDICTION-REQ', field: 'TaxJurisdiction', ruleType: 'Validation', action: 'RaiseError', owner: 'RuleEngine', isActive: true, order: 90 },
      { ruleCode: 'SO-HDR-VALID-TILL-DATE', field: 'ValidTillDate', ruleType: 'Validation', action: 'RaiseWarning', owner: 'RuleEngine', isActive: true, order: 100 },
      { ruleCode: 'SO-HDR-REQUESTED-DATE', field: 'RequestedFulfillmentDate', ruleType: 'Validation', action: 'RaiseWarning', owner: 'RuleEngine', isActive: true, order: 110 },
      { ruleCode: 'SO-HDR-PROMISED-DATE', field: 'PromisedFulfillmentDate', ruleType: 'Validation', action: 'RaiseWarning', owner: 'RuleEngine', isActive: true, order: 120 },
    ],
  },
  {
    ruleSetCode: 'SO_PARTY_RULES',
    ruleSetName: 'Sale Order Party Rules',
    entityName: 'SaleOrder',
    description: 'Customer / party validation, derivation, and masking rules.',
    version: 1,
    isActive: true,
    rules: [
      { ruleCode: 'SO-PARTY-CUSTOMER-MANDATORY', field: 'Customer', ruleType: 'Validation', action: 'RaiseError', owner: 'RuleEngine', isActive: true, order: 10 },
      { ruleCode: 'SO-PARTY-CUSTOMER-ACTIVE', field: 'Customer', ruleType: 'Validation', action: 'RaiseError', owner: 'RuleEngine', isActive: true, order: 20 },
      { ruleCode: 'SO-PARTY-CUSTOMER-DERIVE-CONTACT', field: 'PrimaryContact', ruleType: 'Derivation', action: 'DeriveValue', owner: 'RuleEngine', isActive: true, order: 30 },
      { ruleCode: 'SO-PARTY-CUSTOMER-DERIVE-EMAIL', field: 'Email', ruleType: 'Derivation', action: 'DeriveValue', owner: 'RuleEngine', isActive: true, order: 40 },
      { ruleCode: 'SO-PARTY-CUSTOMER-DERIVE-BILLING-ADDRESS', field: 'BillingAddress', ruleType: 'Derivation', action: 'DeriveValue', owner: 'RuleEngine', isActive: true, order: 50 },
      { ruleCode: 'SO-PARTY-TAX-ID-REQUIRED-WHEN-ENABLED', field: 'PartyTaxIdentifier', ruleType: 'ConditionalValidation', action: 'RaiseError', owner: 'RuleEngine', isActive: true, order: 60 },
      { ruleCode: 'SO-PARTY-MASKING-POLICY', field: 'ContactTaxId', ruleType: 'FieldBehavior', action: 'ApplyMaskingPolicy', owner: 'PrivacyService', isActive: true, order: 70 },
    ],
  },
  {
    ruleSetCode: 'SO_FULFILLMENT_RULES',
    ruleSetName: 'Sale Order Fulfillment Rules',
    entityName: 'SaleOrder',
    description: 'Validates fulfillment address, method, instruction, and preference.',
    version: 1,
    isActive: true,
    rules: [
      { ruleCode: 'SO-FULFILLMENT-ADDRESS-BELONGS-CUSTOMER', field: 'FulfillmentAddress', ruleType: 'Validation', action: 'RaiseError', owner: 'RuleEngine', isActive: true, order: 10 },
      { ruleCode: 'SO-FULFILLMENT-METHOD-VALID', field: 'FulfillmentMethod', ruleType: 'Validation', action: 'RaiseError', owner: 'RuleEngine', isActive: true, order: 20 },
      { ruleCode: 'SO-FULFILLMENT-INSTRUCTION-LENGTH', field: 'FulfillmentInstruction', ruleType: 'Validation', action: 'RaiseWarning', owner: 'RuleEngine', isActive: true, order: 30 },
      { ruleCode: 'SO-FULFILLMENT-PREFERENCE-VALID', field: 'FulfillmentPreferenceType', ruleType: 'Validation', action: 'RaiseError', owner: 'RuleEngine', isActive: true, order: 40 },
    ],
  },
  {
    ruleSetCode: 'SO_PAYMENT_RULES',
    ruleSetName: 'Sale Order Payment Rules',
    entityName: 'SaleOrder',
    description: 'Validates payment mode, method, advance, and terms.',
    version: 1,
    isActive: true,
    rules: [
      { ruleCode: 'SO-PAYMENT-MODE-VALID', field: 'PaymentMode', ruleType: 'Validation', action: 'RaiseError', owner: 'RuleEngine', isActive: true, order: 10 },
      { ruleCode: 'SO-PAYMENT-METHOD-REQ-CASH', field: 'PaymentMethod', ruleType: 'ConditionalValidation', action: 'RaiseError', owner: 'RuleEngine', isActive: true, order: 20 },
      { ruleCode: 'SO-PAYMENT-ADVANCE-NONNEGATIVE', field: 'AdvancePayment', ruleType: 'Validation', action: 'RaiseError', owner: 'RuleEngine', isActive: true, order: 30 },
      { ruleCode: 'SO-PAYMENT-ADVANCE-CONTEXT-ONLY', field: 'AdvancePayment', ruleType: 'BoundaryRule', action: 'RaiseWarning', owner: 'RuleEngine', isActive: true, order: 40 },
      { ruleCode: 'SO-PAYMENT-TERM-VALID', field: 'PaymentTerm', ruleType: 'Validation', action: 'RaiseError', owner: 'RuleEngine', isActive: true, order: 50 },
    ],
  },
  {
    ruleSetCode: 'SO_FINANCE_EXTENSION_RULES',
    ruleSetName: 'Sale Order Finance Extension Rules',
    entityName: 'SaleOrder',
    description: 'Finance fields — only when Finance Sale Extension is enabled.',
    version: 1,
    isActive: true,
    rules: [
      { ruleCode: 'SO-FIN-FINANCIER-REQ-WHEN-FINANCE', field: 'Financier', ruleType: 'ConditionalValidation', action: 'RaiseError', owner: 'RuleEngine', isActive: true, order: 10 },
      { ruleCode: 'SO-FIN-DOWN-PAYMENT-NONNEGATIVE', field: 'DownPayment', ruleType: 'Validation', action: 'RaiseError', owner: 'RuleEngine', isActive: true, order: 20 },
      { ruleCode: 'SO-FIN-FINANCE-AMOUNT-NONNEGATIVE', field: 'FinanceAmount', ruleType: 'Validation', action: 'RaiseError', owner: 'RuleEngine', isActive: true, order: 30 },
      { ruleCode: 'SO-FIN-EMI-NONNEGATIVE', field: 'EmiAmount', ruleType: 'Validation', action: 'RaiseError', owner: 'RuleEngine', isActive: true, order: 40 },
      { ruleCode: 'SO-FIN-INTEREST-NONNEGATIVE', field: 'EmiInterestRate', ruleType: 'Validation', action: 'RaiseError', owner: 'RuleEngine', isActive: true, order: 50 },
      { ruleCode: 'SO-FIN-BALANCE-DERIVATION', field: 'BalanceAmount', ruleType: 'Derivation', action: 'DeriveValue', owner: 'RuleEngine', isActive: true, order: 60 },
    ],
  },
  {
    ruleSetCode: 'SO_INSURANCE_EXTENSION_RULES',
    ruleSetName: 'Sale Order Insurance Extension Rules',
    entityName: 'SaleOrder',
    description: 'Insurance fields — only when Insurance Context Extension is enabled.',
    version: 1,
    isActive: true,
    rules: [
      { ruleCode: 'SO-INS-PROVIDER-VALID', field: 'InsuranceProvider', ruleType: 'Validation', action: 'RaiseError', owner: 'RuleEngine', isActive: true, order: 10 },
      { ruleCode: 'SO-INS-POLICY-NO-VALID', field: 'InsurancePolicyNumber', ruleType: 'Validation', action: 'RaiseWarning', owner: 'RuleEngine', isActive: true, order: 20 },
      { ruleCode: 'SO-INS-POLICY-DATE-VALID', field: 'InsurancePolicyDate', ruleType: 'Validation', action: 'RaiseWarning', owner: 'RuleEngine', isActive: true, order: 30 },
      { ruleCode: 'SO-INS-REMARKS-VALID', field: 'InsuranceRemarks', ruleType: 'Validation', action: 'RaiseWarning', owner: 'RuleEngine', isActive: true, order: 40 },
    ],
  },
  {
    ruleSetCode: 'SO_LINE_VALIDATION_RULES',
    ruleSetName: 'Sale Order Line Validation',
    entityName: 'SaleOrder',
    description: 'Validates all line-level fields including item, qty, rate, discount.',
    version: 1,
    isActive: true,
    rules: [
      { ruleCode: 'SO-LINE-ATLEAST-ONE-LINE', field: 'Lines', ruleType: 'Validation', action: 'RaiseError', owner: 'RuleEngine', isActive: true, order: 10 },
      { ruleCode: 'SO-LINE-ITEM-REQ', field: 'OrderableItem', ruleType: 'Validation', action: 'RaiseError', owner: 'RuleEngine', isActive: true, order: 20 },
      { ruleCode: 'SO-LINE-ITEM-ACTIVE', field: 'OrderableItem', ruleType: 'Validation', action: 'RaiseError', owner: 'RuleEngine', isActive: true, order: 30 },
      { ruleCode: 'SO-LINE-UOM-REQ', field: 'UOM', ruleType: 'Validation', action: 'RaiseError', owner: 'RuleEngine', isActive: true, order: 40 },
      { ruleCode: 'SO-LINE-UOM-VALID-FOR-ITEM', field: 'UOM', ruleType: 'Validation', action: 'RaiseError', owner: 'RuleEngine', isActive: true, order: 50 },
      { ruleCode: 'SO-LINE-QTY-GT-ZERO', field: 'OrderQuantity', ruleType: 'Validation', action: 'RaiseError', owner: 'RuleEngine', isActive: true, order: 60 },
      { ruleCode: 'SO-LINE-QTY-CAPS', field: 'OrderQuantity', ruleType: 'ConditionalValidation', action: 'RaiseWarning', owner: 'RuleEngine', isActive: true, order: 70 },
      { ruleCode: 'SO-LINE-RATE-REQ', field: 'Rate', ruleType: 'Validation', action: 'RaiseError', owner: 'RuleEngine', isActive: true, order: 80 },
      { ruleCode: 'SO-LINE-RATE-NONNEGATIVE', field: 'Rate', ruleType: 'Validation', action: 'RaiseError', owner: 'RuleEngine', isActive: true, order: 90 },
      { ruleCode: 'SO-LINE-DISCOUNT-PERCENT-RANGE', field: 'DiscountPercent', ruleType: 'Validation', action: 'RaiseError', owner: 'RuleEngine', isActive: true, order: 100 },
      { ruleCode: 'SO-LINE-DISCOUNT-AMOUNT-RANGE', field: 'DiscountAmount', ruleType: 'Validation', action: 'RaiseError', owner: 'RuleEngine', isActive: true, order: 110 },
      { ruleCode: 'SO-LINE-TAXABLE-AMOUNT-DERIVE', field: 'TaxableAmount', ruleType: 'Derivation', action: 'DeriveValue', owner: 'RuleEngine', isActive: true, order: 120 },
      { ruleCode: 'SO-LINE-AMOUNT-DERIVE', field: 'LineAmount', ruleType: 'Derivation', action: 'DeriveValue', owner: 'RuleEngine', isActive: true, order: 130 },
    ],
  },
  {
    ruleSetCode: 'SO_PRICING_RULES',
    ruleSetName: 'Sale Order Pricing Rules',
    entityName: 'SaleOrder',
    description: 'Price list derivation, rate validity, and override tolerance rules.',
    version: 1,
    isActive: true,
    rules: [
      { ruleCode: 'SO-PRICE-LIST-DERIVE', field: 'PriceList', ruleType: 'Derivation', action: 'DeriveValue', owner: 'PricingService', isActive: true, order: 10 },
      { ruleCode: 'SO-PRICE-RATE-DEFAULT', field: 'Rate', ruleType: 'Derivation', action: 'DeriveValue', owner: 'PricingService', isActive: true, order: 20 },
      { ruleCode: 'SO-PRICE-RATE-VALIDITY', field: 'Rate', ruleType: 'Validation', action: 'RaiseError', owner: 'PricingService', isActive: true, order: 30 },
      { ruleCode: 'SO-PRICE-OVERRIDE-TOLERANCE', field: 'Rate', ruleType: 'ApprovalTrigger', action: 'RequireApproval', owner: 'RuleEngine', isActive: true, order: 40 },
      { ruleCode: 'SO-PRICE-ENGINE-REFERENCE', field: 'PricingEngineReference', ruleType: 'Derivation', action: 'DeriveValue', owner: 'PricingService', isActive: true, order: 50 },
    ],
  },
  {
    ruleSetCode: 'SO_DISCOUNT_RULES',
    ruleSetName: 'Sale Order Discount Rules',
    entityName: 'SaleOrder',
    description: 'Discount validation and approval trigger rules.',
    version: 1,
    isActive: true,
    rules: [
      { ruleCode: 'SO-DISC-PERCENT-VALID', field: 'DiscountPercent', ruleType: 'Validation', action: 'RaiseError', owner: 'RuleEngine', isActive: true, order: 10 },
      { ruleCode: 'SO-DISC-AMOUNT-VALID', field: 'DiscountAmount', ruleType: 'Validation', action: 'RaiseError', owner: 'RuleEngine', isActive: true, order: 20 },
      { ruleCode: 'SO-DISC-AMOUNT-MATCH', field: 'DiscountAmount', ruleType: 'Validation', action: 'RaiseWarning', owner: 'RuleEngine', isActive: true, order: 30 },
      { ruleCode: 'SO-DISC-LIMIT-CHECK', field: 'DiscountPercent', ruleType: 'ApprovalTrigger', action: 'RequireApproval', owner: 'RuleEngine', isActive: true, order: 40 },
      { ruleCode: 'SO-DISC-PRICE-IMPACT', field: 'DiscountAmount', ruleType: 'Derivation', action: 'DeriveValue', owner: 'DiscountService', isActive: true, order: 50 },
      { ruleCode: 'SO-DISC-APPROVAL-CATEGORY', field: 'DiscountPercent', ruleType: 'ApprovalTrigger', action: 'RequireApproval', owner: 'RuleEngine', isActive: true, order: 60 },
    ],
  },
  {
    ruleSetCode: 'SO_TAX_RULES',
    ruleSetName: 'Sale Order Tax Rules',
    entityName: 'SaleOrder',
    description: 'Tax jurisdiction, classification, and calculation rules.',
    version: 1,
    isActive: true,
    rules: [
      { ruleCode: 'SO-TAX-JURISDICTION-REQ', field: 'TaxJurisdiction', ruleType: 'Validation', action: 'RaiseError', owner: 'RuleEngine', isActive: true, order: 10 },
      { ruleCode: 'SO-TAX-CLASSIFICATION-REQ', field: 'TaxClassificationCode', ruleType: 'Validation', action: 'RaiseError', owner: 'RuleEngine', isActive: true, order: 20 },
      { ruleCode: 'SO-TAX-PARTY-ID-CHECK', field: 'PartyTaxIdentifier', ruleType: 'ConditionalValidation', action: 'RaiseError', owner: 'RuleEngine', isActive: true, order: 30 },
      { ruleCode: 'SO-TAX-CALCULATE', field: 'TaxSummary', ruleType: 'SystemInvariant', action: 'CallService', owner: 'TaxService', isActive: true, order: 40 },
      { ruleCode: 'SO-TAX-ENGINE-REFERENCE', field: 'TaxEngineReference', ruleType: 'Derivation', action: 'DeriveValue', owner: 'TaxService', isActive: true, order: 50 },
      { ruleCode: 'SO-TAX-LOCALIZATION-ROUTE', field: 'GeographyExtension', ruleType: 'Eligibility', action: 'RouteToExtension', owner: 'TaxService', isActive: true, order: 60 },
    ],
  },
  {
    ruleSetCode: 'SO_CHARGE_RULES',
    ruleSetName: 'Sale Order Charge Rules',
    entityName: 'SaleOrder',
    description: 'Additional charge applicability, calculation, and validation.',
    version: 1,
    isActive: true,
    rules: [
      { ruleCode: 'SO-CHARGE-APPLICABILITY', field: 'Charges', ruleType: 'Eligibility', action: 'DeriveValue', owner: 'ChargeService', isActive: true, order: 10 },
      { ruleCode: 'SO-CHARGE-CALCULATE', field: 'ChargeAmount', ruleType: 'SystemInvariant', action: 'CallService', owner: 'ChargeService', isActive: true, order: 20 },
      { ruleCode: 'SO-CHARGE-VALIDATE', field: 'ChargeAmount', ruleType: 'Validation', action: 'RaiseWarning', owner: 'RuleEngine', isActive: true, order: 30 },
      { ruleCode: 'SO-CHARGE-ENGINE-REFERENCE', field: 'ChargeEngineReference', ruleType: 'Derivation', action: 'DeriveValue', owner: 'ChargeService', isActive: true, order: 40 },
    ],
  },
  {
    ruleSetCode: 'SO_TOTAL_CALCULATION_RULES',
    ruleSetName: 'Sale Order Total Calculation',
    entityName: 'SaleOrder',
    description: 'Derives all totals: qty, base, discount, tax, charges, net amount.',
    version: 1,
    isActive: true,
    rules: [
      { ruleCode: 'SO-CALC-TOTAL-QTY', field: 'TotalQuantity', ruleType: 'Derivation', action: 'DeriveValue', owner: 'CalculationService', isActive: true, order: 10 },
      { ruleCode: 'SO-CALC-TOTAL-BASE-AMOUNT', field: 'TotalBaseAmount', ruleType: 'Derivation', action: 'DeriveValue', owner: 'CalculationService', isActive: true, order: 20 },
      { ruleCode: 'SO-CALC-TOTAL-DISCOUNT', field: 'TotalDiscountAmount', ruleType: 'Derivation', action: 'DeriveValue', owner: 'CalculationService', isActive: true, order: 30 },
      { ruleCode: 'SO-CALC-TOTAL-TAX', field: 'TotalTaxAmount', ruleType: 'Derivation', action: 'DeriveValue', owner: 'TaxService', isActive: true, order: 40 },
      { ruleCode: 'SO-CALC-TOTAL-AMOUNT', field: 'TotalAmount', ruleType: 'Derivation', action: 'DeriveValue', owner: 'CalculationService', isActive: true, order: 50 },
      { ruleCode: 'SO-CALC-NET-AMOUNT', field: 'NetAmount', ruleType: 'Derivation', action: 'DeriveValue', owner: 'CalculationService', isActive: true, order: 60 },
      { ruleCode: 'SO-CALC-ROUNDING', field: 'RoundingAdjustment', ruleType: 'Derivation', action: 'DeriveValue', owner: 'CurrencyService', isActive: true, order: 70 },
    ],
  },
  {
    ruleSetCode: 'SO_APPROVAL_TRIGGER_RULES',
    ruleSetName: 'Sale Order Approval Trigger Rules',
    entityName: 'SaleOrder',
    description: 'Detects conditions that require approval and sets approval category.',
    version: 1,
    isActive: true,
    rules: [
      { ruleCode: 'SO-APR-DISCOUNT-EXCEPTION', field: 'DiscountPercent', ruleType: 'ApprovalTrigger', action: 'RequireApproval', owner: 'RuleEngine', isActive: true, order: 10 },
      { ruleCode: 'SO-APR-PRICE-OVERRIDE', field: 'Rate', ruleType: 'ApprovalTrigger', action: 'RequireApproval', owner: 'RuleEngine', isActive: true, order: 20 },
      { ruleCode: 'SO-APR-CREDIT-EXCEPTION', field: 'CreditPolicy', ruleType: 'ApprovalTrigger', action: 'RequireApproval', owner: 'RuleEngine', isActive: true, order: 30 },
      { ruleCode: 'SO-APR-TAX-EXCEPTION', field: 'TaxOverride', ruleType: 'ApprovalTrigger', action: 'RequireApproval', owner: 'RuleEngine', isActive: true, order: 40 },
      { ruleCode: 'SO-APR-EXPIRED-ORDER', field: 'ValidTillDate', ruleType: 'ApprovalTrigger', action: 'RequireApproval', owner: 'RuleEngine', isActive: true, order: 50 },
      { ruleCode: 'SO-APR-PROCESSED-AMENDMENT', field: 'AmendmentAfterProcessing', ruleType: 'ApprovalTrigger', action: 'RequireApproval', owner: 'RuleEngine', isActive: true, order: 60 },
      { ruleCode: 'SO-APR-CANCELLATION', field: 'CancellationAfterProcessing', ruleType: 'ApprovalTrigger', action: 'RequireApproval', owner: 'RuleEngine', isActive: true, order: 70 },
    ],
  },
  {
    ruleSetCode: 'SO_LIFECYCLE_RULES',
    ruleSetName: 'Sale Order Lifecycle Rules',
    entityName: 'SaleOrder',
    description: 'Status derivation and lifecycle transition rules.',
    version: 1,
    isActive: true,
    rules: [
      { ruleCode: 'SO-LC-DRAFT-STATUS', ruleType: 'StatusDerivation', action: 'DeriveValue', owner: 'Workflow', isActive: true, order: 10 },
      { ruleCode: 'SO-LC-OPEN-STATUS', ruleType: 'StatusDerivation', action: 'DeriveValue', owner: 'Workflow', isActive: true, order: 20 },
      { ruleCode: 'SO-LC-PENDING-APPROVAL', ruleType: 'StatusDerivation', action: 'DeriveValue', owner: 'Workflow', isActive: true, order: 30 },
      { ruleCode: 'SO-LC-APPROVED', ruleType: 'StatusDerivation', action: 'DeriveValue', owner: 'Workflow', isActive: true, order: 40 },
      { ruleCode: 'SO-LC-REJECTED', ruleType: 'StatusDerivation', action: 'DeriveValue', owner: 'Workflow', isActive: true, order: 50 },
      { ruleCode: 'SO-LC-HOLD', ruleType: 'StatusDerivation', action: 'DeriveValue', owner: 'Workflow', isActive: true, order: 60 },
      { ruleCode: 'SO-LC-RELEASE', ruleType: 'StatusDerivation', action: 'DeriveValue', owner: 'Workflow', isActive: true, order: 70 },
      { ruleCode: 'SO-LC-CANCELLED', ruleType: 'StatusDerivation', action: 'DeriveValue', owner: 'Workflow', isActive: true, order: 80 },
      { ruleCode: 'SO-LC-CLOSED', ruleType: 'StatusDerivation', action: 'DeriveValue', owner: 'Workflow', isActive: true, order: 90 },
      { ruleCode: 'SO-LC-REOPENED', ruleType: 'StatusDerivation', action: 'DeriveValue', owner: 'Workflow', isActive: true, order: 100 },
      { ruleCode: 'SO-LC-EXPIRED', ruleType: 'StatusDerivation', action: 'DeriveValue', owner: 'LifecycleService', isActive: true, order: 110 },
    ],
  },
  {
    ruleSetCode: 'SO_HOLD_RELEASE_RULES',
    ruleSetName: 'Sale Order Hold / Release Rules',
    entityName: 'SaleOrder',
    description: 'Validates hold type, reason, and authority for hold and release actions.',
    version: 1,
    isActive: true,
    rules: [
      { ruleCode: 'SO-HOLD-TYPE-REQ', field: 'HoldType', ruleType: 'Validation', action: 'RaiseError', owner: 'RuleEngine', isActive: true, order: 10 },
      { ruleCode: 'SO-HOLD-REASON-REQ', field: 'HoldReason', ruleType: 'Validation', action: 'RaiseError', owner: 'RuleEngine', isActive: true, order: 20 },
      { ruleCode: 'SO-HOLD-AUTHORITY', field: 'HoldAuthority', ruleType: 'Validation', action: 'RaiseError', owner: 'RBACService', isActive: true, order: 30 },
      { ruleCode: 'SO-HOLD-BLOCKED-ACTIONS', ruleType: 'FieldBehavior', action: 'SetFieldBehavior', owner: 'RuleEngine', isActive: true, order: 40 },
      { ruleCode: 'SO-REL-REASON-REQ', field: 'ReleaseReason', ruleType: 'Validation', action: 'RaiseError', owner: 'RuleEngine', isActive: true, order: 50 },
      { ruleCode: 'SO-REL-AUTHORITY', field: 'ReleaseAuthority', ruleType: 'Validation', action: 'RaiseError', owner: 'RBACService', isActive: true, order: 60 },
    ],
  },
  {
    ruleSetCode: 'SO_CANCELLATION_RULES',
    ruleSetName: 'Sale Order Cancellation Rules',
    entityName: 'SaleOrder',
    description: 'Validates cancellation eligibility and quantity protection.',
    version: 1,
    isActive: true,
    rules: [
      { ruleCode: 'SO-CAN-REASON-REQ', field: 'CancellationReason', ruleType: 'Validation', action: 'RaiseError', owner: 'RuleEngine', isActive: true, order: 10 },
      { ruleCode: 'SO-CAN-NOT-IF-FULLY-PROCESSED', field: 'ProcessedScope', ruleType: 'Validation', action: 'RaiseError', owner: 'SourceLineLedgerService', isActive: true, order: 20 },
      { ruleCode: 'SO-CAN-QTY-NOT-GT-PENDING', field: 'CancelQuantity', ruleType: 'Validation', action: 'RaiseError', owner: 'RuleEngine', isActive: true, order: 30 },
      { ruleCode: 'SO-CAN-APPROVAL-IF-PROCESSED', field: 'ProcessedScope', ruleType: 'ApprovalTrigger', action: 'RequireApproval', owner: 'RuleEngine', isActive: true, order: 40 },
      { ruleCode: 'SO-CAN-STATUS-ASSIGN', ruleType: 'StatusDerivation', action: 'DeriveValue', owner: 'Workflow', isActive: true, order: 50 },
    ],
  },
  {
    ruleSetCode: 'SO_AMENDMENT_RULES',
    ruleSetName: 'Sale Order Amendment Rules',
    entityName: 'SaleOrder',
    description: 'Amendment reason, revision, processed scope, and audit rules.',
    version: 1,
    isActive: true,
    rules: [
      { ruleCode: 'SO-AMD-REASON-REQ', field: 'AmendmentReason', ruleType: 'Validation', action: 'RaiseError', owner: 'RuleEngine', isActive: true, order: 10 },
      { ruleCode: 'SO-AMD-REVISION-NO-DERIVE', field: 'RevisionNumber', ruleType: 'Derivation', action: 'DeriveValue', owner: 'RevisionService', isActive: true, order: 20 },
      { ruleCode: 'SO-AMD-PROCESSED-SCOPE-CHECK', field: 'ProcessedScope', ruleType: 'Validation', action: 'RaiseError', owner: 'SourceLineLedgerService', isActive: true, order: 30 },
      { ruleCode: 'SO-AMD-APPROVAL-IF-PROCESSED', field: 'ProcessedScope', ruleType: 'ApprovalTrigger', action: 'RequireApproval', owner: 'RuleEngine', isActive: true, order: 40 },
      { ruleCode: 'SO-AMD-AUDIT-BEFORE-AFTER', ruleType: 'SystemInvariant', action: 'CallService', owner: 'AuditService', isActive: true, order: 50 },
    ],
  },
  {
    ruleSetCode: 'SO_DOWNSTREAM_PROTECTION_RULES',
    ruleSetName: 'Sale Order Downstream Protection Rules',
    entityName: 'SaleOrder',
    description: 'Makes processed fields readonly and protects consumed quantities.',
    version: 1,
    isActive: true,
    rules: [
      { ruleCode: 'SO-DS-ALLOCATION-READONLY', field: 'AllocationFields', ruleType: 'FieldBehavior', action: 'SetFieldBehavior', owner: 'RuleEngine', isActive: true, order: 10 },
      { ruleCode: 'SO-DS-INVOICE-READONLY', field: 'InvoiceFields', ruleType: 'FieldBehavior', action: 'SetFieldBehavior', owner: 'RuleEngine', isActive: true, order: 20 },
      { ruleCode: 'SO-DS-DELIVERY-READONLY', field: 'DeliveryFields', ruleType: 'FieldBehavior', action: 'SetFieldBehavior', owner: 'RuleEngine', isActive: true, order: 30 },
      { ruleCode: 'SO-DS-RETURN-READONLY', field: 'ReturnFields', ruleType: 'FieldBehavior', action: 'SetFieldBehavior', owner: 'RuleEngine', isActive: true, order: 40 },
      { ruleCode: 'SO-DS-CONSUMED-QTY-READONLY', field: 'ConsumedQuantity', ruleType: 'FieldBehavior', action: 'SetFieldBehavior', owner: 'RuleEngine', isActive: true, order: 50 },
      { ruleCode: 'SO-DS-PENDING-QTY-NONNEGATIVE', field: 'PendingQuantity', ruleType: 'Validation', action: 'RaiseError', owner: 'SourceLineLedgerService', isActive: true, order: 60 },
      { ruleCode: 'SO-DS-REVERSAL-EVENT-ONLY', field: 'Reversal', ruleType: 'BoundaryRule', action: 'CallService', owner: 'IntegrationEventService', isActive: true, order: 70 },
      { ruleCode: 'SO-DS-TRACEABILITY-REQ', field: 'DownstreamUpdate', ruleType: 'Validation', action: 'RaiseError', owner: 'SourceLineLedgerService', isActive: true, order: 80 },
    ],
  },
  {
    ruleSetCode: 'SO_SHORTCUT_ELIGIBILITY_RULES',
    ruleSetName: 'Sale Order Shortcut Eligibility Rules',
    entityName: 'SaleOrder',
    description: 'Determines eligibility for downstream shortcut actions.',
    version: 1,
    isActive: true,
    rules: [
      { ruleCode: 'SO-SC-ALLOCATION-REQ-ELIGIBLE', field: 'SaleAllocationRequisition', ruleType: 'Eligibility', action: 'DeriveValue', owner: 'RuleEngine', isActive: true, order: 10 },
      { ruleCode: 'SO-SC-ALLOCATION-ELIGIBLE', field: 'SaleAllocation', ruleType: 'Eligibility', action: 'DeriveValue', owner: 'RuleEngine', isActive: true, order: 20 },
      { ruleCode: 'SO-SC-INVOICE-ELIGIBLE', field: 'SaleInvoice', ruleType: 'Eligibility', action: 'DeriveValue', owner: 'RuleEngine', isActive: true, order: 30 },
      { ruleCode: 'SO-SC-DELIVERY-ELIGIBLE', field: 'Delivery', ruleType: 'Eligibility', action: 'DeriveValue', owner: 'RuleEngine', isActive: true, order: 40 },
      { ruleCode: 'SO-SC-RETURN-ELIGIBLE', field: 'SaleReturn', ruleType: 'Eligibility', action: 'DeriveValue', owner: 'RuleEngine', isActive: true, order: 50 },
      { ruleCode: 'SO-SC-CHILD-REVALIDATE-SOURCE', field: 'ChildDocument', ruleType: 'Validation', action: 'RaiseError', owner: 'SourceLineLedgerService', isActive: true, order: 60 },
    ],
  },
  {
    ruleSetCode: 'SO_SECURITY_FIELD_BEHAVIOR_RULES',
    ruleSetName: 'Sale Order Security Field Behavior Rules',
    entityName: 'SaleOrder',
    description: 'RBAC and role-based field visibility / readonly rules.',
    version: 1,
    isActive: true,
    rules: [
      { ruleCode: 'SO-SEC-RBAC-FIELD-VISIBLE', ruleType: 'FieldBehavior', action: 'SetFieldBehavior', owner: 'RBACService', isActive: true, order: 10 },
      { ruleCode: 'SO-SEC-RBAC-FIELD-EDITABLE', ruleType: 'FieldBehavior', action: 'SetFieldBehavior', owner: 'RBACService', isActive: true, order: 20 },
      { ruleCode: 'SO-SEC-SENSITIVE-MASKING', ruleType: 'FieldBehavior', action: 'ApplyMaskingPolicy', owner: 'PrivacyService', isActive: true, order: 30 },
    ],
  },
];
