// Service registry seed data — 12 service definitions.
// Backend seeding reference only.

import type { ServiceConfig } from '../types/configuration';

const DEFAULT_RETRY: ServiceConfig['retryPolicy'] = {
  maxRetries: 3,
  retryDelayMs: 500,
  backoffMultiplier: 2,
};

export const SERVICE_REGISTRY_SEED: ServiceConfig[] = [
  {
    serviceCode: 'SaleOrderService',
    serviceName: 'Sale Order Service',
    endpointUrl: '/api/services/sale-order',
    timeoutMs: 10000,
    retryPolicy: DEFAULT_RETRY,
    fallbackPolicy: 'ReturnError',
    isActive: true,
    actionCodes: ['CREATE_DRAFT', 'UPDATE_DRAFT', 'SUBMIT_ORDER', 'CANCEL_ORDER', 'HOLD_ORDER', 'RELEASE_ORDER', 'AMEND_ORDER', 'CLOSE_ORDER', 'REOPEN_ORDER'],
  },
  {
    serviceCode: 'NumberingService',
    serviceName: 'Numbering Service',
    endpointUrl: '/api/services/numbering',
    timeoutMs: 5000,
    retryPolicy: DEFAULT_RETRY,
    fallbackPolicy: 'ReturnError',
    isActive: true,
    actionCodes: ['GENERATE_DOCUMENT_NUMBER'],
  },
  {
    serviceCode: 'PricingService',
    serviceName: 'Pricing Service',
    endpointUrl: '/api/services/pricing',
    timeoutMs: 8000,
    retryPolicy: DEFAULT_RETRY,
    fallbackPolicy: 'ReturnError',
    isActive: true,
    actionCodes: ['CALCULATE_PRICING', 'VALIDATE_PRICE_OVERRIDE', 'REPRICE_ORDER'],
  },
  {
    serviceCode: 'DiscountService',
    serviceName: 'Discount Service',
    endpointUrl: '/api/services/discount',
    timeoutMs: 5000,
    retryPolicy: DEFAULT_RETRY,
    fallbackPolicy: 'ReturnError',
    isActive: true,
    actionCodes: ['CALCULATE_DISCOUNT', 'VALIDATE_DISCOUNT'],
  },
  {
    serviceCode: 'TaxService',
    serviceName: 'Tax Service',
    endpointUrl: '/api/services/tax',
    timeoutMs: 8000,
    retryPolicy: DEFAULT_RETRY,
    fallbackPolicy: 'ReturnError',
    isActive: true,
    actionCodes: ['DERIVE_TAX_CONTEXT', 'VALIDATE_TAX_CONTEXT', 'CALCULATE_TAX'],
  },
  {
    serviceCode: 'ChargeService',
    serviceName: 'Charge Service',
    endpointUrl: '/api/services/charge',
    timeoutMs: 5000,
    retryPolicy: DEFAULT_RETRY,
    fallbackPolicy: 'ReturnError',
    isActive: true,
    actionCodes: ['CALCULATE_CHARGES', 'VALIDATE_CHARGES'],
  },
  {
    serviceCode: 'CurrencyService',
    serviceName: 'Currency Service',
    endpointUrl: '/api/services/currency',
    timeoutMs: 5000,
    retryPolicy: DEFAULT_RETRY,
    fallbackPolicy: 'UseLastKnown',
    isActive: true,
    actionCodes: ['DERIVE_CURRENCY', 'GET_EXCHANGE_RATE', 'APPLY_ROUNDING'],
  },
  {
    serviceCode: 'ApprovalService',
    serviceName: 'Approval Service',
    endpointUrl: '/api/services/approval',
    timeoutMs: 10000,
    retryPolicy: DEFAULT_RETRY,
    fallbackPolicy: 'ReturnError',
    isActive: true,
    actionCodes: ['CREATE_APPROVAL_CASE', 'WAIT_FOR_APPROVAL', 'CAPTURE_DECISION', 'ESCALATE'],
  },
  {
    serviceCode: 'AuditService',
    serviceName: 'Audit Service',
    endpointUrl: '/api/services/audit',
    timeoutMs: 3000,
    retryPolicy: { maxRetries: 5, retryDelayMs: 200, backoffMultiplier: 1 },
    fallbackPolicy: 'SkipStep',
    isActive: true,
    actionCodes: ['WRITE_AUDIT_EVENT', 'WRITE_STATUS_AUDIT', 'WRITE_APPROVAL_AUDIT'],
  },
  {
    serviceCode: 'IntegrationEventService',
    serviceName: 'Integration Event Service',
    endpointUrl: '/api/services/integration-event',
    timeoutMs: 5000,
    retryPolicy: { maxRetries: 5, retryDelayMs: 1000, backoffMultiplier: 2 },
    fallbackPolicy: 'ReturnError',
    isActive: true,
    actionCodes: ['PUBLISH_DRAFT_CREATED', 'PUBLISH_SUBMITTED', 'PUBLISH_APPROVED', 'PUBLISH_CANCELLED', 'PUBLISH_DOWNSTREAM_READY'],
  },
  {
    serviceCode: 'NotificationService',
    serviceName: 'Notification Service',
    endpointUrl: '/api/services/notification',
    timeoutMs: 5000,
    retryPolicy: { maxRetries: 2, retryDelayMs: 500, backoffMultiplier: 1 },
    fallbackPolicy: 'SkipStep',
    isActive: true,
    actionCodes: ['NOTIFY_CREATION', 'NOTIFY_APPROVAL_PENDING', 'NOTIFY_APPROVAL_DECISION', 'NOTIFY_CANCELLATION'],
  },
  {
    serviceCode: 'SourceLineLedgerService',
    serviceName: 'Source Line Ledger Service',
    endpointUrl: '/api/services/source-line-ledger',
    timeoutMs: 8000,
    retryPolicy: DEFAULT_RETRY,
    fallbackPolicy: 'ReturnError',
    isActive: true,
    actionCodes: ['GENERATE_SOURCE_LINE_REFERENCE', 'VALIDATE_PROCESSED_SCOPE', 'VALIDATE_PENDING_QUANTITY', 'UPDATE_SOURCE_LINE_LEDGER'],
  },
];
