// Seed data for all 7 Sale Order workflow definitions — derived from blueprint Section 8 & 10.
// Backend seeding reference only. Not loaded at runtime.

import type { WorkflowConfig } from '../types/configuration';

export const SALE_ORDER_WORKFLOW_SEED: WorkflowConfig[] = [
  {
    workflowCode: 'WF_SO_DRAFT_SAVE',
    workflowName: 'Sale Order Draft Save',
    entityName: 'SaleOrder',
    version: 1,
    description: 'Save a sale order as draft without submitting for processing.',
    isActive: true,
    steps: [
      { seq: 10, stepCode: 'START', stepType: 'Start', calls: '-', failureBehavior: 'Stop', isActive: true },
      { seq: 20, stepCode: 'RESOLVE_CONTEXT', stepType: 'ServiceTask', calls: 'ContextService.resolve', failureBehavior: 'Stop', isActive: true },
      { seq: 30, stepCode: 'PRE_VALIDATE', stepType: 'RuleTask', calls: 'SO_PRE_VALIDATION_RULES', failureBehavior: 'ValidationFailed', isActive: true },
      { seq: 40, stepCode: 'GENERATE_DOCUMENT_NUMBER', stepType: 'ServiceTask', calls: 'NumberingService.generate', failureBehavior: 'Stop', isActive: true },
      { seq: 50, stepCode: 'CREATE_DRAFT', stepType: 'ServiceTask', calls: 'SaleOrderService.createDraft', failureBehavior: 'Stop', isActive: true },
      { seq: 60, stepCode: 'SYSTEM_DERIVATION', stepType: 'ServiceTask', calls: 'SaleOrderService.deriveSystemFields', failureBehavior: 'Stop', isActive: true },
      { seq: 70, stepCode: 'BASIC_HEADER_VALIDATE', stepType: 'RuleTask', calls: 'SO_HEADER_VALIDATION_RULES', failureBehavior: 'ValidationFailed', isActive: true },
      { seq: 80, stepCode: 'BASIC_LINE_VALIDATE', stepType: 'RuleTask', calls: 'SO_LINE_VALIDATION_RULES', failureBehavior: 'ValidationFailed', isActive: true },
      { seq: 90, stepCode: 'CALCULATE_DRAFT_TOTALS', stepType: 'ServiceTask', calls: 'CalculationService.calculateTotals', failureBehavior: 'NonBlocking', isActive: true },
      { seq: 100, stepCode: 'WRITE_AUDIT', stepType: 'ServiceTask', calls: 'AuditService.writeEvent', failureBehavior: 'NonBlocking', isActive: true },
      { seq: 110, stepCode: 'PUBLISH_DRAFT_CREATED', stepType: 'IntegrationTask', calls: 'IntegrationEventService.publish', failureBehavior: 'NonBlocking', isActive: true },
      { seq: 120, stepCode: 'END', stepType: 'End', calls: '-', failureBehavior: 'Stop', isActive: true },
    ],
    transitions: [
      { fromStep: 'START', toStep: 'RESOLVE_CONTEXT' },
      { fromStep: 'RESOLVE_CONTEXT', toStep: 'PRE_VALIDATE' },
      { fromStep: 'PRE_VALIDATE', toStep: 'GENERATE_DOCUMENT_NUMBER' },
      { fromStep: 'GENERATE_DOCUMENT_NUMBER', toStep: 'CREATE_DRAFT' },
      { fromStep: 'CREATE_DRAFT', toStep: 'SYSTEM_DERIVATION' },
      { fromStep: 'SYSTEM_DERIVATION', toStep: 'BASIC_HEADER_VALIDATE' },
      { fromStep: 'BASIC_HEADER_VALIDATE', toStep: 'BASIC_LINE_VALIDATE' },
      { fromStep: 'BASIC_LINE_VALIDATE', toStep: 'CALCULATE_DRAFT_TOTALS' },
      { fromStep: 'CALCULATE_DRAFT_TOTALS', toStep: 'WRITE_AUDIT' },
      { fromStep: 'WRITE_AUDIT', toStep: 'PUBLISH_DRAFT_CREATED' },
      { fromStep: 'PUBLISH_DRAFT_CREATED', toStep: 'END' },
    ],
  },
  {
    workflowCode: 'WF_SO_SUBMIT',
    workflowName: 'Sale Order Submit',
    entityName: 'SaleOrder',
    version: 1,
    description: 'Submit a saved draft sale order for downstream readiness.',
    isActive: true,
    steps: [
      { seq: 10, stepCode: 'START', stepType: 'Start', calls: '-', failureBehavior: 'Stop', isActive: true },
      { seq: 20, stepCode: 'RESOLVE_CONTEXT', stepType: 'ServiceTask', calls: 'ContextService.resolve', failureBehavior: 'Stop', isActive: true },
      { seq: 30, stepCode: 'PRE_VALIDATE', stepType: 'RuleTask', calls: 'SO_PRE_VALIDATION_RULES', failureBehavior: 'ValidationFailed', isActive: true },
      { seq: 40, stepCode: 'GENERATE_DOCUMENT_NUMBER', stepType: 'ServiceTask', calls: 'NumberingService.generate', failureBehavior: 'Stop', isActive: true },
      { seq: 50, stepCode: 'CREATE_DRAFT', stepType: 'ServiceTask', calls: 'SaleOrderService.createDraft', failureBehavior: 'Stop', isActive: true },
      { seq: 60, stepCode: 'SYSTEM_DERIVATION', stepType: 'ServiceTask', calls: 'SaleOrderService.deriveSystemFields', failureBehavior: 'Stop', isActive: true },
      { seq: 70, stepCode: 'HEADER_VALIDATE', stepType: 'RuleTask', calls: 'SO_HEADER_VALIDATION_RULES', failureBehavior: 'ValidationFailed', isActive: true },
      { seq: 80, stepCode: 'PARTY_VALIDATE', stepType: 'RuleTask', calls: 'SO_PARTY_RULES', failureBehavior: 'ValidationFailed', isActive: true },
      { seq: 90, stepCode: 'LINE_VALIDATE', stepType: 'RuleTask', calls: 'SO_LINE_VALIDATION_RULES', failureBehavior: 'ValidationFailed', isActive: true },
      { seq: 100, stepCode: 'PAYMENT_VALIDATE', stepType: 'RuleTask', calls: 'SO_PAYMENT_RULES', failureBehavior: 'ValidationFailed', isActive: true },
      { seq: 110, stepCode: 'FULFILLMENT_VALIDATE', stepType: 'RuleTask', calls: 'SO_FULFILLMENT_RULES', failureBehavior: 'ValidationFailed', isActive: true },
      { seq: 120, stepCode: 'PRICING_SERVICE', stepType: 'ServiceTask', calls: 'PricingService.calculate', failureBehavior: 'Stop', isActive: true },
      { seq: 130, stepCode: 'PRICING_RULES', stepType: 'RuleTask', calls: 'SO_PRICING_RULES', failureBehavior: 'ValidationFailed', isActive: true },
      { seq: 140, stepCode: 'DISCOUNT_SERVICE', stepType: 'ServiceTask', calls: 'DiscountService.calculate', failureBehavior: 'Stop', isActive: true },
      { seq: 150, stepCode: 'DISCOUNT_RULES', stepType: 'RuleTask', calls: 'SO_DISCOUNT_RULES', failureBehavior: 'ValidationFailed', isActive: true },
      { seq: 160, stepCode: 'TAX_CONTEXT', stepType: 'ServiceTask', calls: 'TaxService.deriveContext', failureBehavior: 'Stop', isActive: true },
      { seq: 170, stepCode: 'TAX_RULES', stepType: 'RuleTask', calls: 'SO_TAX_RULES', failureBehavior: 'ValidationFailed', isActive: true },
      { seq: 180, stepCode: 'TAX_SERVICE', stepType: 'ServiceTask', calls: 'TaxService.calculate', failureBehavior: 'Stop', isActive: true },
      { seq: 190, stepCode: 'CHARGE_SERVICE', stepType: 'ServiceTask', calls: 'ChargeService.calculate', failureBehavior: 'Stop', isActive: true },
      { seq: 200, stepCode: 'TOTAL_CALCULATION', stepType: 'ServiceTask', calls: 'CalculationService.calculateTotals', failureBehavior: 'Stop', isActive: true },
      { seq: 210, stepCode: 'APPROVAL_TRIGGER_RULES', stepType: 'RuleTask', calls: 'SO_APPROVAL_TRIGGER_RULES', failureBehavior: 'ValidationFailed', isActive: true },
      { seq: 220, stepCode: 'APPROVAL_REQUIRED_DECISION', stepType: 'Decision', calls: 'result.approvalRequired', failureBehavior: 'Stop', isActive: true },
      { seq: 230, stepCode: 'CREATE_APPROVAL_CASE', stepType: 'ServiceTask', calls: 'ApprovalService.createCase', failureBehavior: 'Stop', isActive: true },
      { seq: 240, stepCode: 'WAIT_FOR_APPROVAL', stepType: 'UserTask', calls: 'ApprovalService.wait', failureBehavior: 'PendingApproval', isActive: true },
      { seq: 250, stepCode: 'APPROVAL_OUTCOME_DECISION', stepType: 'Decision', calls: 'Approved/Rejected/Returned', failureBehavior: 'Stop', isActive: true },
      { seq: 260, stepCode: 'FINAL_DOWNSTREAM_PROTECTION', stepType: 'RuleTask', calls: 'SO_DOWNSTREAM_PROTECTION_RULES', failureBehavior: 'ValidationFailed', isActive: true },
      { seq: 270, stepCode: 'MARK_DOWNSTREAM_READY', stepType: 'ServiceTask', calls: 'SaleOrderService.markDownstreamReady', failureBehavior: 'Stop', isActive: true },
      { seq: 280, stepCode: 'SUBMIT_OR_OPEN', stepType: 'ServiceTask', calls: 'SaleOrderService.submitOrOpen', failureBehavior: 'Stop', isActive: true },
      { seq: 290, stepCode: 'WRITE_AUDIT', stepType: 'ServiceTask', calls: 'AuditService.writeEvent', failureBehavior: 'NonBlocking', isActive: true },
      { seq: 300, stepCode: 'PUBLISH_EVENT', stepType: 'IntegrationTask', calls: 'IntegrationEventService.publish', failureBehavior: 'Retry', isActive: true },
      { seq: 310, stepCode: 'NOTIFY', stepType: 'NotificationTask', calls: 'NotificationService.send', failureBehavior: 'NonBlocking', isActive: true },
      { seq: 320, stepCode: 'END', stepType: 'End', calls: '-', failureBehavior: 'Stop', isActive: true },
    ],
    transitions: [],
  },
  {
    workflowCode: 'WF_SO_APPROVAL',
    workflowName: 'Sale Order Approval',
    entityName: 'SaleOrder',
    version: 1,
    description: 'Manages approval case and resumes sale order workflow after decision.',
    isActive: true,
    steps: [
      { seq: 10, stepCode: 'START', stepType: 'Start', calls: '-', failureBehavior: 'Stop', isActive: true },
      { seq: 20, stepCode: 'LOAD_APPROVAL_CASE', stepType: 'ServiceTask', calls: 'ApprovalService.getCase', failureBehavior: 'Stop', isActive: true },
      { seq: 30, stepCode: 'VALIDATE_APPROVER', stepType: 'RuleTask', calls: 'SO_SECURITY_FIELD_BEHAVIOR_RULES', failureBehavior: 'Stop', isActive: true },
      { seq: 40, stepCode: 'CAPTURE_DECISION', stepType: 'UserTask', calls: 'ApprovalService.captureDecision', failureBehavior: 'Stop', isActive: true },
      { seq: 50, stepCode: 'DECISION_OUTCOME', stepType: 'Decision', calls: 'Approved/Rejected/Returned/Escalated', failureBehavior: 'Stop', isActive: true },
      { seq: 60, stepCode: 'WRITE_AUDIT', stepType: 'ServiceTask', calls: 'AuditService.writeAudit', failureBehavior: 'NonBlocking', isActive: true },
      { seq: 70, stepCode: 'NOTIFY', stepType: 'NotificationTask', calls: 'NotificationService.send', failureBehavior: 'NonBlocking', isActive: true },
      { seq: 80, stepCode: 'END', stepType: 'End', calls: '-', failureBehavior: 'Stop', isActive: true },
    ],
    transitions: [],
  },
  {
    workflowCode: 'WF_SO_HOLD',
    workflowName: 'Sale Order Hold',
    entityName: 'SaleOrder',
    version: 1,
    description: 'Places a sale order on hold.',
    isActive: true,
    steps: [
      { seq: 10, stepCode: 'START', stepType: 'Start', calls: '-', failureBehavior: 'Stop', isActive: true },
      { seq: 20, stepCode: 'LOAD_SALE_ORDER', stepType: 'ServiceTask', calls: 'SaleOrderService.load', failureBehavior: 'Stop', isActive: true },
      { seq: 30, stepCode: 'VALIDATE_HOLD_RULES', stepType: 'RuleTask', calls: 'SO_HOLD_RELEASE_RULES', failureBehavior: 'ValidationFailed', isActive: true },
      { seq: 40, stepCode: 'VALIDATE_PERMISSION', stepType: 'ServiceTask', calls: 'RBACService.validate', failureBehavior: 'Stop', isActive: true },
      { seq: 50, stepCode: 'CREATE_HOLD', stepType: 'ServiceTask', calls: 'SaleOrderService.holdOrder', failureBehavior: 'Stop', isActive: true },
      { seq: 60, stepCode: 'UPDATE_STATUS', stepType: 'ServiceTask', calls: 'SaleOrderService.updateStatus', failureBehavior: 'Stop', isActive: true },
      { seq: 70, stepCode: 'WRITE_AUDIT', stepType: 'ServiceTask', calls: 'AuditService.writeEvent', failureBehavior: 'NonBlocking', isActive: true },
      { seq: 80, stepCode: 'NOTIFY', stepType: 'NotificationTask', calls: 'NotificationService.send', failureBehavior: 'NonBlocking', isActive: true },
      { seq: 90, stepCode: 'END', stepType: 'End', calls: '-', failureBehavior: 'Stop', isActive: true },
    ],
    transitions: [],
  },
  {
    workflowCode: 'WF_SO_RELEASE',
    workflowName: 'Sale Order Release',
    entityName: 'SaleOrder',
    version: 1,
    description: 'Releases a sale order from hold.',
    isActive: true,
    steps: [
      { seq: 10, stepCode: 'START', stepType: 'Start', calls: '-', failureBehavior: 'Stop', isActive: true },
      { seq: 20, stepCode: 'LOAD_SALE_ORDER', stepType: 'ServiceTask', calls: 'SaleOrderService.load', failureBehavior: 'Stop', isActive: true },
      { seq: 30, stepCode: 'VALIDATE_RELEASE_RULES', stepType: 'RuleTask', calls: 'SO_HOLD_RELEASE_RULES', failureBehavior: 'ValidationFailed', isActive: true },
      { seq: 40, stepCode: 'VALIDATE_PERMISSION', stepType: 'ServiceTask', calls: 'RBACService.validate', failureBehavior: 'Stop', isActive: true },
      { seq: 50, stepCode: 'RELEASE_HOLD', stepType: 'ServiceTask', calls: 'SaleOrderService.releaseOrder', failureBehavior: 'Stop', isActive: true },
      { seq: 60, stepCode: 'RESTORE_STATUS', stepType: 'ServiceTask', calls: 'SaleOrderService.updateStatus', failureBehavior: 'Stop', isActive: true },
      { seq: 70, stepCode: 'WRITE_AUDIT', stepType: 'ServiceTask', calls: 'AuditService.writeEvent', failureBehavior: 'NonBlocking', isActive: true },
      { seq: 80, stepCode: 'NOTIFY', stepType: 'NotificationTask', calls: 'NotificationService.send', failureBehavior: 'NonBlocking', isActive: true },
      { seq: 90, stepCode: 'END', stepType: 'End', calls: '-', failureBehavior: 'Stop', isActive: true },
    ],
    transitions: [],
  },
  {
    workflowCode: 'WF_SO_CANCEL',
    workflowName: 'Sale Order Cancel',
    entityName: 'SaleOrder',
    version: 1,
    description: 'Cancels a sale order with processed scope protection and optional approval.',
    isActive: true,
    steps: [
      { seq: 10, stepCode: 'START', stepType: 'Start', calls: '-', failureBehavior: 'Stop', isActive: true },
      { seq: 20, stepCode: 'LOAD_SALE_ORDER', stepType: 'ServiceTask', calls: 'SaleOrderService.load', failureBehavior: 'Stop', isActive: true },
      { seq: 30, stepCode: 'VALIDATE_CANCELLATION_RULES', stepType: 'RuleTask', calls: 'SO_CANCELLATION_RULES', failureBehavior: 'ValidationFailed', isActive: true },
      { seq: 40, stepCode: 'VALIDATE_PROCESSED_SCOPE', stepType: 'ServiceTask', calls: 'SourceLineLedgerService.validateScope', failureBehavior: 'Stop', isActive: true },
      { seq: 50, stepCode: 'APPROVAL_TRIGGER_RULES', stepType: 'RuleTask', calls: 'SO_APPROVAL_TRIGGER_RULES', failureBehavior: 'ValidationFailed', isActive: true },
      { seq: 60, stepCode: 'APPROVAL_DECISION', stepType: 'Decision', calls: 'result.approvalRequired', failureBehavior: 'Stop', isActive: true },
      { seq: 70, stepCode: 'CANCEL_ORDER', stepType: 'ServiceTask', calls: 'SaleOrderService.cancelOrder', failureBehavior: 'Stop', isActive: true },
      { seq: 80, stepCode: 'UPDATE_SOURCE_LINE_LEDGER', stepType: 'ServiceTask', calls: 'SourceLineLedgerService.update', failureBehavior: 'Stop', isActive: true },
      { seq: 90, stepCode: 'WRITE_AUDIT', stepType: 'ServiceTask', calls: 'AuditService.writeEvent', failureBehavior: 'NonBlocking', isActive: true },
      { seq: 100, stepCode: 'PUBLISH_CANCELLED', stepType: 'IntegrationTask', calls: 'IntegrationEventService.publish', failureBehavior: 'Retry', isActive: true },
      { seq: 110, stepCode: 'NOTIFY', stepType: 'NotificationTask', calls: 'NotificationService.send', failureBehavior: 'NonBlocking', isActive: true },
      { seq: 120, stepCode: 'END', stepType: 'End', calls: '-', failureBehavior: 'Stop', isActive: true },
    ],
    transitions: [],
  },
  {
    workflowCode: 'WF_SO_AMEND',
    workflowName: 'Sale Order Amend',
    entityName: 'SaleOrder',
    version: 1,
    description: 'Amends a sale order with revision tracking and processed scope protection.',
    isActive: true,
    steps: [
      { seq: 10, stepCode: 'START', stepType: 'Start', calls: '-', failureBehavior: 'Stop', isActive: true },
      { seq: 20, stepCode: 'LOAD_SALE_ORDER', stepType: 'ServiceTask', calls: 'SaleOrderService.load', failureBehavior: 'Stop', isActive: true },
      { seq: 30, stepCode: 'VALIDATE_AMENDMENT_RULES', stepType: 'RuleTask', calls: 'SO_AMENDMENT_RULES', failureBehavior: 'ValidationFailed', isActive: true },
      { seq: 40, stepCode: 'VALIDATE_PROCESSED_SCOPE', stepType: 'ServiceTask', calls: 'SourceLineLedgerService.validateScope', failureBehavior: 'Stop', isActive: true },
      { seq: 50, stepCode: 'CREATE_REVISION', stepType: 'ServiceTask', calls: 'RevisionService.createRevision', failureBehavior: 'Stop', isActive: true },
      { seq: 60, stepCode: 'APPLY_CHANGES', stepType: 'ServiceTask', calls: 'SaleOrderService.amendOrder', failureBehavior: 'Stop', isActive: true },
      { seq: 70, stepCode: 'RECALCULATE', stepType: 'ServiceTask', calls: 'CalculationService.recalculate', failureBehavior: 'Stop', isActive: true },
      { seq: 80, stepCode: 'APPROVAL_TRIGGER_RULES', stepType: 'RuleTask', calls: 'SO_APPROVAL_TRIGGER_RULES', failureBehavior: 'ValidationFailed', isActive: true },
      { seq: 90, stepCode: 'APPROVAL_DECISION', stepType: 'Decision', calls: 'result.approvalRequired', failureBehavior: 'Stop', isActive: true },
      { seq: 100, stepCode: 'WRITE_AUDIT', stepType: 'ServiceTask', calls: 'AuditService.writeEvent', failureBehavior: 'NonBlocking', isActive: true },
      { seq: 110, stepCode: 'PUBLISH_AMENDED', stepType: 'IntegrationTask', calls: 'IntegrationEventService.publish', failureBehavior: 'Retry', isActive: true },
      { seq: 120, stepCode: 'NOTIFY', stepType: 'NotificationTask', calls: 'NotificationService.send', failureBehavior: 'NonBlocking', isActive: true },
      { seq: 130, stepCode: 'END', stepType: 'End', calls: '-', failureBehavior: 'Stop', isActive: true },
    ],
    transitions: [],
  },
];
