// ─── Service Type Master — Constants ─────────────────────────────────────────

import type {
  ServiceTypeRecord,
  PostingType,
  BillingRatioType,
  AllocationType,
  ContractOperator,
  ServiceDeliveryMode,
  ServiceSourceApplicability,
  AssetIdentificationLevel,
  MeterReadingType,
  DurationType,
  DurationTypeShort,
  OperatorType,
  ServiceProviderType,
  SkillProficiencyLevel,
  WarrantyEligibilityBasis,
  BillingResponsibility,
  RelationType,
  LogicOp,
  CategoryType,
  SLACalendarType,
} from '../types/serviceTypeMaster.types';

export const MASTER_KEY = 'service-type-master';

// ─── Picklist Options ─────────────────────────────────────────────────────────

export const POSTING_TYPE_OPTIONS: PostingType[] = ['Paid', 'Expenses', 'Generate Claim'];

export const BILLING_RATIO_TYPE_OPTIONS: BillingRatioType[] = ['Percentage', 'Amount'];

export const ALLOCATION_TYPE_OPTIONS: AllocationType[] = ['Change'];

export const CONTRACT_OPERATOR_OPTIONS: ContractOperator[] = [
  'ONLY DAYS', 'And', 'OR', 'Only KM', 'Maximum',
];

export const SERVICE_DELIVERY_MODE_OPTIONS: ServiceDeliveryMode[] = [
  'On-site', 'Workshop', 'Remote', 'Depot', 'Pickup & Drop',
];

export const SERVICE_SOURCE_OPTIONS: ServiceSourceApplicability[] = [
  'Complaint', 'Contract', 'Warranty', 'Scheduled PM', 'IoT Alert', 'Customer Request',
];

export const ASSET_ID_LEVEL_OPTIONS: AssetIdentificationLevel[] = [
  'Product', 'Serial Number', 'IMEI', 'VIN', 'Equipment Number', 'Meter', 'Location',
];

export const METER_READING_TYPE_OPTIONS: MeterReadingType[] = [
  'KM', 'Hours', 'Cycles', 'Units', 'Runtime', 'Print Count',
];

export const DURATION_TYPE_OPTIONS: DurationType[] = ['Days', 'Weeks', 'Months', 'Years'];

export const DURATION_TYPE_SHORT_OPTIONS: DurationTypeShort[] = ['Days', 'Month', 'Year'];

export const OPERATOR_OPTIONS: OperatorType[] = ['AND', 'OR'];

export const SERVICE_PROVIDER_TYPE_OPTIONS: ServiceProviderType[] = [
  'In-house', 'Dealer', 'Authorized Service Center', 'OEM', 'Third-party', 'Partner',
];

export const SKILL_PROFICIENCY_OPTIONS: SkillProficiencyLevel[] = [
  'Junior', 'Senior', 'Expert', 'OEM Certified',
];

export const WARRANTY_BASIS_OPTIONS: WarrantyEligibilityBasis[] = [
  'Sale Date', 'Installation Date', 'Usage', 'Contract', 'Serial Number', 'Claim Policy',
];

export const BILLING_RESPONSIBILITY_OPTIONS: BillingResponsibility[] = [
  'Customer Paid', 'OEM Paid', 'Insurance Paid', 'Warranty Paid', 'Dealer Paid', 'Contract Paid',
];

export const RELATION_TYPE_OPTIONS: RelationType[] = [
  'Service Details', 'Item Details', 'Vehicle Contract Applicable',
  'Service Contract Applicable', 'Item Contract Applicable',
];

export const LOGIC_OP_OPTIONS: LogicOp[] = ['AND', 'OR'];

export const CATEGORY_TYPE_OPTIONS: CategoryType[] = ['Individual', 'Group'];

export const SLA_CALENDAR_OPTIONS: SLACalendarType[] = [
  'Business Hours', '24x7', 'Customer Calendar',
];

// Mock lookup lists for prototype
export const MOCK_SERVICE_TYPES = [
  { code: 'ST-001', name: 'Annual Maintenance Contract' },
  { code: 'ST-002', name: 'Warranty Service' },
  { code: 'ST-003', name: 'Breakdown Service' },
  { code: 'ST-004', name: 'Preventive Maintenance' },
];

export const MOCK_PRODUCTS = [
  { code: 'PRD-001', name: 'Air Conditioner 1.5 Ton' },
  { code: 'PRD-002', name: 'Refrigerator 250L' },
  { code: 'PRD-003', name: 'Washing Machine 7Kg' },
  { code: 'PRD-004', name: 'Microwave Oven 30L' },
];

export const MOCK_SERVICES = [
  { code: 'SRV-001', name: 'Gas Filling' },
  { code: 'SRV-002', name: 'Compressor Replacement' },
  { code: 'SRV-003', name: 'Filter Cleaning' },
  { code: 'SRV-004', name: 'PCB Repair' },
];

export const MOCK_PARTS = [
  { code: 'PRT-001', name: 'Compressor' },
  { code: 'PRT-002', name: 'Capacitor' },
  { code: 'PRT-003', name: 'Thermostat' },
  { code: 'PRT-004', name: 'PCB Board' },
];

export const MOCK_SUPPLIERS = [
  { code: 'SUP-001', name: 'OEM Direct' },
  { code: 'SUP-002', name: 'Regional Distributor' },
];

export const MOCK_ATTRIBUTES = [
  { code: 'ATTR-001', name: 'Voltage', type: 'Number' },
  { code: 'ATTR-002', name: 'Refrigerant Type', type: 'Text' },
  { code: 'ATTR-003', name: 'Tonnage', type: 'Decimal' },
];

export const MOCK_SKILLS = ['Refrigeration', 'Electronics', 'Hydraulics', 'Electrical'];
export const MOCK_CERTIFICATIONS = ['ISO 9001', 'OEM Certified', 'Safety L1', 'Safety L2'];
export const MOCK_TERRITORIES = ['North Zone', 'South Zone', 'East Zone', 'West Zone', 'All India'];
export const MOCK_CHECKLIST_TEMPLATES = ['Safety Template A', 'Pre-Service Standard', 'Post-Service Standard'];
export const MOCK_SLA_PROFILES = ['Gold SLA', 'Silver SLA', 'Standard SLA', 'Critical SLA'];
export const MOCK_CONTRACTS = ['AMC-2026', 'WARRANTY-2026', 'EW-2026'];
export const MOCK_SEGMENTS = ['Residential', 'Commercial', 'Industrial'];
export const MOCK_SUBSEGMENTS = ['HVAC', 'Appliances', 'Pumps'];
export const MOCK_ORGS = ['HQ', 'North Region', 'South Region'];

// ─── Seed Data ────────────────────────────────────────────────────────────────

export const SEED_SERVICE_TYPES: ServiceTypeRecord[] = [
  {
    id: 'st-001',
    status: 'Active',
    code: 'ST-001',
    codeOverride: false,
    name: 'Annual Maintenance Contract',
    postingType: 'Paid',
    description: 'Comprehensive yearly maintenance covering all parts and labour.',
    saleable: true,
    taxExempted: false,
    subscriptionApplicable: true,
    separateBillRequired: false,
    contractRequired: true,
    generateReminder: true,
    applicableToAllParts: false,
    applicableToAllServices: false,
    applicableToAllProducts: true,
    isRatioApplicable: false,
    billingRatioType: '',
    billingRatioRows: [],
    isHeader: true,
    isLine: false,
    availWithUCN: false,
    availMultipleTimes: false,
    availLimit: '1',
    active: true,
    discontinued: false,
    copyToWarrantyTab: false,
    availedAtOrganization: false,
    isCustom: false,
    claimTo: '',
    contractOperator: '',
    defaultMaxDuration: '365',
    defaultMaxUsage: '',
    applicableContract: '',
    dependentContract: '',
    childContractActive: false,
    childContracts: [],
    childLabours: [],
    segmentType: 'Residential',
    subSegmentType: 'HVAC',
    organization: '',
    serviceDeliveryMode: 'On-site',
    serviceRequestSourceApplicability: ['Contract', 'Scheduled PM'],
    remoteServiceAllowed: false,
    remoteDiagnosisRequired: false,
    installedAssetRequired: true,
    assetIdentificationLevel: 'Serial Number',
    multiAssetServiceAllowed: false,
    meterReadingRequired: false,
    meterReadingType: '',
    meterReading: '',
    durationType: '',
    durationValue: '',
    operator: '',
    serviceTypeTagging: [],
    standardServiceDuration: '2',
    serviceTimeWindowRequired: true,
    defaultServiceWindowFrom: '09:00',
    defaultServiceWindowTo: '17:00',
    applicableServiceTerritory: ['North Zone', 'South Zone'],
    serviceProviderType: 'In-house',
    requiredSkill: ['Refrigeration'],
    requiredCertification: [],
    skillProficiencyLevel: 'Senior',
    minimumTechnicianCount: '1',
    crewRequired: false,
    safetyPermitRequired: false,
    safetyChecklistTemplate: '',
    preServiceChecklistTemplate: 'Pre-Service Standard',
    postServiceChecklistTemplate: 'Post-Service Standard',
    testInspectionEvidenceRequired: false,
    complaintReviewRequired: false,
    slaProfile: 'Gold SLA',
    responseSLA: '4',
    resolutionSLA: '24',
    slaCalendar: 'Business Hours',
    approvalRequired: false,
    warrantyEligibilityBasis: '',
    billingResponsibility: 'Customer Paid',
    visitChargeApplicable: false,
    diagnosisChargeApplicable: false,
    pickupAndDropRequired: false,
    closureEvidenceRequired: true,
    followUpRequired: true,
    followUpInterval: '3',
    knowledgeArticleReference: '',
    offlineExecutionAllowed: true,
    productCategory: '',
    productApplicabilityRows: [],
    labourRows: [],
    partRows: [],
    attributeTagRows: [],
    createdBy: 'Admin',
    createdDate: '2026-01-10 09:00',
    lastModifiedBy: 'Admin',
    lastModifiedDate: '2026-01-10 09:00',
  },
  {
    id: 'st-002',
    status: 'Active',
    code: 'ST-002',
    codeOverride: false,
    name: 'Warranty Service',
    postingType: 'Generate Claim',
    description: 'OEM warranty service for defective parts within warranty period.',
    saleable: false,
    taxExempted: true,
    subscriptionApplicable: false,
    separateBillRequired: false,
    contractRequired: false,
    generateReminder: false,
    applicableToAllParts: false,
    applicableToAllServices: false,
    applicableToAllProducts: true,
    isRatioApplicable: false,
    billingRatioType: '',
    billingRatioRows: [],
    isHeader: true,
    isLine: true,
    availWithUCN: false,
    availMultipleTimes: false,
    availLimit: '1',
    active: true,
    discontinued: false,
    copyToWarrantyTab: true,
    availedAtOrganization: false,
    isCustom: false,
    claimTo: 'SUP-001',
    contractOperator: '',
    defaultMaxDuration: '',
    defaultMaxUsage: '',
    applicableContract: '',
    dependentContract: '',
    childContractActive: false,
    childContracts: [],
    childLabours: [],
    segmentType: '',
    subSegmentType: '',
    organization: '',
    serviceDeliveryMode: 'Workshop',
    serviceRequestSourceApplicability: ['Warranty', 'Complaint'],
    remoteServiceAllowed: false,
    remoteDiagnosisRequired: false,
    installedAssetRequired: true,
    assetIdentificationLevel: 'Serial Number',
    multiAssetServiceAllowed: false,
    meterReadingRequired: false,
    meterReadingType: '',
    meterReading: '',
    durationType: '',
    durationValue: '',
    operator: '',
    serviceTypeTagging: [],
    standardServiceDuration: '4',
    serviceTimeWindowRequired: false,
    defaultServiceWindowFrom: '',
    defaultServiceWindowTo: '',
    applicableServiceTerritory: [],
    serviceProviderType: 'Authorized Service Center',
    requiredSkill: [],
    requiredCertification: ['OEM Certified'],
    skillProficiencyLevel: 'Expert',
    minimumTechnicianCount: '1',
    crewRequired: false,
    safetyPermitRequired: false,
    safetyChecklistTemplate: '',
    preServiceChecklistTemplate: '',
    postServiceChecklistTemplate: 'Post-Service Standard',
    testInspectionEvidenceRequired: true,
    complaintReviewRequired: false,
    slaProfile: 'Standard SLA',
    responseSLA: '8',
    resolutionSLA: '48',
    slaCalendar: 'Business Hours',
    approvalRequired: false,
    warrantyEligibilityBasis: 'Sale Date',
    billingResponsibility: 'OEM Paid',
    visitChargeApplicable: false,
    diagnosisChargeApplicable: false,
    pickupAndDropRequired: false,
    closureEvidenceRequired: true,
    followUpRequired: false,
    followUpInterval: '',
    knowledgeArticleReference: '',
    offlineExecutionAllowed: false,
    productCategory: '',
    productApplicabilityRows: [],
    labourRows: [],
    partRows: [],
    attributeTagRows: [],
    createdBy: 'Admin',
    createdDate: '2026-01-12 10:30',
    lastModifiedBy: 'Admin',
    lastModifiedDate: '2026-01-12 10:30',
  },
  {
    id: 'st-003',
    status: 'Draft',
    code: 'ST-003',
    codeOverride: false,
    name: 'Breakdown Service',
    postingType: 'Paid',
    description: 'Emergency repair service for out-of-order equipment.',
    saleable: true,
    taxExempted: false,
    subscriptionApplicable: false,
    separateBillRequired: false,
    contractRequired: false,
    generateReminder: false,
    applicableToAllParts: false,
    applicableToAllServices: false,
    applicableToAllProducts: false,
    isRatioApplicable: false,
    billingRatioType: '',
    billingRatioRows: [],
    isHeader: true,
    isLine: false,
    availWithUCN: false,
    availMultipleTimes: true,
    availLimit: '',
    active: false,
    discontinued: false,
    copyToWarrantyTab: false,
    availedAtOrganization: false,
    isCustom: false,
    claimTo: '',
    contractOperator: '',
    defaultMaxDuration: '',
    defaultMaxUsage: '',
    applicableContract: '',
    dependentContract: '',
    childContractActive: false,
    childContracts: [],
    childLabours: [],
    segmentType: '',
    subSegmentType: '',
    organization: '',
    serviceDeliveryMode: 'On-site',
    serviceRequestSourceApplicability: ['Complaint', 'Customer Request'],
    remoteServiceAllowed: false,
    remoteDiagnosisRequired: true,
    installedAssetRequired: false,
    assetIdentificationLevel: '',
    multiAssetServiceAllowed: false,
    meterReadingRequired: false,
    meterReadingType: '',
    meterReading: '',
    durationType: '',
    durationValue: '',
    operator: '',
    serviceTypeTagging: [],
    standardServiceDuration: '3',
    serviceTimeWindowRequired: false,
    defaultServiceWindowFrom: '',
    defaultServiceWindowTo: '',
    applicableServiceTerritory: [],
    serviceProviderType: '',
    requiredSkill: [],
    requiredCertification: [],
    skillProficiencyLevel: '',
    minimumTechnicianCount: '1',
    crewRequired: false,
    safetyPermitRequired: false,
    safetyChecklistTemplate: '',
    preServiceChecklistTemplate: '',
    postServiceChecklistTemplate: '',
    testInspectionEvidenceRequired: false,
    complaintReviewRequired: false,
    slaProfile: '',
    responseSLA: '2',
    resolutionSLA: '8',
    slaCalendar: '',
    approvalRequired: false,
    warrantyEligibilityBasis: '',
    billingResponsibility: 'Customer Paid',
    visitChargeApplicable: true,
    diagnosisChargeApplicable: true,
    pickupAndDropRequired: false,
    closureEvidenceRequired: false,
    followUpRequired: false,
    followUpInterval: '',
    knowledgeArticleReference: '',
    offlineExecutionAllowed: false,
    productCategory: '',
    productApplicabilityRows: [],
    labourRows: [],
    partRows: [],
    attributeTagRows: [],
    createdBy: 'Admin',
    createdDate: '2026-02-01 11:00',
    lastModifiedBy: 'Admin',
    lastModifiedDate: '2026-02-01 11:00',
  },
];

// ─── Empty / Initial Record ───────────────────────────────────────────────────

export const INITIAL_SERVICE_TYPE: Omit<ServiceTypeRecord, 'id' | 'code' | 'createdBy' | 'createdDate' | 'lastModifiedBy' | 'lastModifiedDate'> = {
  status: 'Draft',
  codeOverride: false,
  name: '',
  postingType: 'Paid',
  description: '',
  saleable: false,
  taxExempted: false,
  subscriptionApplicable: false,
  separateBillRequired: false,
  contractRequired: false,
  generateReminder: false,
  applicableToAllParts: false,
  applicableToAllServices: false,
  applicableToAllProducts: false,
  isRatioApplicable: false,
  billingRatioType: '',
  billingRatioRows: [],
  isHeader: false,
  isLine: false,
  availWithUCN: false,
  availMultipleTimes: false,
  availLimit: '',
  active: false,
  discontinued: false,
  copyToWarrantyTab: false,
  availedAtOrganization: false,
  isCustom: false,
  claimTo: '',
  contractOperator: '',
  defaultMaxDuration: '',
  defaultMaxUsage: '',
  applicableContract: '',
  dependentContract: '',
  childContractActive: false,
  childContracts: [],
  childLabours: [],
  segmentType: '',
  subSegmentType: '',
  organization: '',
  serviceDeliveryMode: '',
  serviceRequestSourceApplicability: [],
  remoteServiceAllowed: false,
  remoteDiagnosisRequired: false,
  installedAssetRequired: false,
  assetIdentificationLevel: '',
  multiAssetServiceAllowed: false,
  meterReadingRequired: false,
  meterReadingType: '',
  meterReading: '',
  durationType: '',
  durationValue: '',
  operator: '',
  serviceTypeTagging: [],
  standardServiceDuration: '',
  serviceTimeWindowRequired: false,
  defaultServiceWindowFrom: '',
  defaultServiceWindowTo: '',
  applicableServiceTerritory: [],
  serviceProviderType: '',
  requiredSkill: [],
  requiredCertification: [],
  skillProficiencyLevel: '',
  minimumTechnicianCount: '',
  crewRequired: false,
  safetyPermitRequired: false,
  safetyChecklistTemplate: '',
  preServiceChecklistTemplate: '',
  postServiceChecklistTemplate: '',
  testInspectionEvidenceRequired: false,
  complaintReviewRequired: false,
  slaProfile: '',
  responseSLA: '',
  resolutionSLA: '',
  slaCalendar: '',
  approvalRequired: false,
  warrantyEligibilityBasis: '',
  billingResponsibility: '',
  visitChargeApplicable: false,
  diagnosisChargeApplicable: false,
  pickupAndDropRequired: false,
  closureEvidenceRequired: false,
  followUpRequired: false,
  followUpInterval: '',
  knowledgeArticleReference: '',
  offlineExecutionAllowed: false,
  productCategory: '',
  productApplicabilityRows: [],
  labourRows: [],
  partRows: [],
  attributeTagRows: [],
};

// ─── Service Profile Presets ─────────────────────────────────────────────────────────

export type ServiceProfile = 'warranty' | 'contract' | 'saleable' | 'periodic' | 'field' | 'custom';

export const PROFILE_PRESETS: Record<ServiceProfile, Partial<ServiceTypeRecord>> = {
  warranty: {
    postingType: 'Generate Claim',
    contractRequired: true,
    installedAssetRequired: true,
    generateReminder: true,
    isHeader: true,
    isLine: true,
    active: true,
    warrantyEligibilityBasis: 'Sale Date',
    billingResponsibility: 'Warranty Paid',
    serviceDeliveryMode: 'On-site',
    testInspectionEvidenceRequired: true,
    serviceRequestSourceApplicability: ['Warranty', 'Complaint'],
  },
  contract: {
    postingType: 'Paid',
    contractRequired: true,
    saleable: true,
    isHeader: true,
    isLine: true,
    active: true,
    billingResponsibility: 'Contract Paid',
    serviceRequestSourceApplicability: ['Contract', 'Scheduled PM'],
  },
  saleable: {
    postingType: 'Paid',
    contractRequired: false,
    saleable: true,
    isHeader: false,
    isLine: true,
    active: true,
    billingResponsibility: 'Customer Paid',
    serviceRequestSourceApplicability: ['Customer Request'],
  },
  periodic: {
    postingType: 'Paid',
    contractRequired: true,
    installedAssetRequired: true,
    isHeader: false,
    isLine: true,
    active: true,
    generateReminder: true,
    billingResponsibility: 'Contract Paid',
    serviceRequestSourceApplicability: ['Scheduled PM', 'Contract'],
  },
  field: {
    postingType: 'Paid',
    saleable: true,
    contractRequired: false,
    remoteServiceAllowed: false,
    serviceDeliveryMode: 'On-site',
    isHeader: false,
    isLine: true,
    active: true,
    billingResponsibility: 'Customer Paid',
    serviceRequestSourceApplicability: ['Complaint', 'Customer Request'],
  },
  custom: {},
};

// Wizard steps (0-indexed) to skip per profile. User can override by clicking the step.
export const PROFILE_SKIP_STEPS: Record<ServiceProfile, number[]> = {
  warranty: [],
  contract: [],
  saleable: [2, 4],  // skip Asset & Scheduling, Safety & SLA
  periodic: [4],     // skip Safety & SLA
  field:    [4],     // skip Safety & SLA
  custom:   [],
};
