// ─── Slot Master — TypeScript Types ──────────────────────────────────────────

export type SlotStatus = 'Draft' | 'Active' | 'Inactive';

export type DayOfWeek = 'Mon' | 'Tue' | 'Wed' | 'Thu' | 'Fri' | 'Sat' | 'Sun';

// ─── Sub-entities ─────────────────────────────────────────────────────────────

export interface TaggedEmployee {
  employeeId: string;
  employeeName: string;
  role: string;
}

export interface GeneratedSlot {
  startTime: string; // "09:00"
  endTime: string;   // "09:30"
  assignedEmployeeId?: string;
}

export interface GeneratedDay {
  date: string;       // ISO "2026-06-01"
  dayLabel: string;   // "Mon, 01 Jun"
  slots: GeneratedSlot[];
}

// ─── Main Entity ──────────────────────────────────────────────────────────────

export interface SlotRecord {
  id: string;
  /** Auto-generated e.g. SLT-0001 */
  slotCode: string;
  name: string;
  displayName: string;
  entity: string;
  entityTypes: string[];
  /** Role Master id — drives employee auto-tagging */
  tagToRole: string;
  taggedEmployees: TaggedEmployee[];
  /** Branch id (mocked until Branch Master is built) */
  branch: string;
  startDate: string; // ISO date
  endDate: string;   // ISO date
  slotStartTime: string; // "HH:MM"
  slotEndTime: string;   // "HH:MM"
  slotDurationMin: number;
  timeGapMin: number;
  activeDays: DayOfWeek[];
  /** Autogenerated — slots per working day */
  dailySlotCount: number;
  /** Autogenerated — total slots across all days */
  totalSlotCount: number;
  /** Autogenerated — number of working days in range */
  totalDays: number;
  description: string;
  isActive: boolean;
  status: SlotStatus;
  generatedDays: GeneratedDay[];
  createdAt?: string;
  updatedAt?: string;
}

// ─── Form Errors ──────────────────────────────────────────────────────────────

export interface SlotFormErrors {
  name?: string;
  entity?: string;
  startDate?: string;
  endDate?: string;
  slotStartTime?: string;
  slotEndTime?: string;
  slotDurationMin?: string;
  activeDays?: string;
  general?: string;
}

// ─── Branch calendar shape (mocked) ──────────────────────────────────────────

export interface BranchBreak {
  name: string;
  start: string; // "HH:MM"
  end: string;
}

export interface MockBranch {
  id: string;
  name: string;
  workStart: string;
  workEnd: string;
  breaks: BranchBreak[];
  workingDays: DayOfWeek[];
  holidays: string[]; // ISO dates
}

// ─── Role / Employee shapes (mocked) ─────────────────────────────────────────

export interface MockRole {
  id: string;
  name: string;
}

export interface MockEmployee {
  id: string;
  name: string;
  roleId: string;
  isActive: boolean;
}
