// ─── Area Master — Seed Data ──────────────────────────────────────────────────

import type { AreaLevel, Area } from '../types/areaMaster.types';

// ─── Seed Area Levels ─────────────────────────────────────────────────────────

export const SEED_AREA_LEVELS: AreaLevel[] = [
  {
    id: 'ARLVL-0001',
    areaLevelCode: 'ARLVL-0001',
    areaLevelName: 'Country',
    displayName: 'Country',
    shortCode: 'CTY',
    levelSequence: 1,
    areaLevelRole: 'Structural',
    parentRequired: false,
    allowedParentLevelIds: [],
    allowedUsageTags: ['Geographic', 'Reporting'],
    defaultUsageTags: [],
    mandatoryUsageTags: ['Geographic'],
    status: 'Active',
    description: 'Top-level geographic unit representing a country.',
    remarks: '',
    createdAt: '2025-01-01T00:00:00.000Z',
    updatedAt: '2025-01-01T00:00:00.000Z',
  },
  {
    id: 'ARLVL-0002',
    areaLevelCode: 'ARLVL-0002',
    areaLevelName: 'State / Province',
    displayName: 'State / Province',
    shortCode: 'STP',
    levelSequence: 2,
    areaLevelRole: 'Structural',
    parentRequired: true,
    allowedParentLevelIds: ['ARLVL-0001'],
    allowedUsageTags: ['Geographic', 'Reporting'],
    defaultUsageTags: [],
    mandatoryUsageTags: ['Geographic'],
    status: 'Active',
    description: 'State or province within a country.',
    remarks: '',
    createdAt: '2025-01-01T00:00:00.000Z',
    updatedAt: '2025-01-01T00:00:00.000Z',
  },
  {
    id: 'ARLVL-0003',
    areaLevelCode: 'ARLVL-0003',
    areaLevelName: 'City',
    displayName: 'City',
    shortCode: 'CTY3',
    levelSequence: 3,
    areaLevelRole: 'Structural + Operational',
    parentRequired: true,
    allowedParentLevelIds: ['ARLVL-0002'],
    allowedUsageTags: ['Geographic', 'Sales', 'Service', 'Delivery', 'Reporting'],
    defaultUsageTags: [],
    mandatoryUsageTags: ['Geographic'],
    status: 'Active',
    description: 'City within a state or province.',
    remarks: '',
    createdAt: '2025-01-01T00:00:00.000Z',
    updatedAt: '2025-01-01T00:00:00.000Z',
  },
  {
    id: 'ARLVL-0004',
    areaLevelCode: 'ARLVL-0004',
    areaLevelName: 'Area',
    displayName: 'Area',
    shortCode: 'AREA',
    levelSequence: 4,
    areaLevelRole: 'Operational',
    parentRequired: true,
    allowedParentLevelIds: ['ARLVL-0003'],
    allowedUsageTags: ['Sales', 'Service', 'Delivery', 'Collection', 'Reporting'],
    defaultUsageTags: ['Sales', 'Service'],
    mandatoryUsageTags: [],
    status: 'Active',
    description: 'Operational area within a city used for sales, service and delivery.',
    remarks: '',
    createdAt: '2025-01-01T00:00:00.000Z',
    updatedAt: '2025-01-01T00:00:00.000Z',
  },
];

// ─── Seed Areas ───────────────────────────────────────────────────────────────

export const SEED_AREAS: Area[] = [
  {
    id: 'AREA-0001',
    areaCode: 'AREA-0001',
    areaName: 'India',
    displayName: 'India',
    externalLegacyCode: '',
    areaLevelId: 'ARLVL-0001',
    parentAreaId: null,
    hierarchyPath: 'India',
    usageTags: ['Geographic', 'Reporting'],
    areaCategory: '',
    areaClassification: '',
    postalCode: '',
    latitude: null,
    longitude: null,
    geoBoundaryType: 'Not Applicable',
    radiusValue: null,
    radiusUnit: '',
    polygonReference: '',
    mapProvider: '',
    externalBoundaryId: '',
    aliases: [],
    status: 'Active',
    description: '',
    remarks: '',
    createdAt: '2025-01-01T00:00:00.000Z',
    updatedAt: '2025-01-01T00:00:00.000Z',
  },
  {
    id: 'AREA-0002',
    areaCode: 'AREA-0002',
    areaName: 'Maharashtra',
    displayName: 'Maharashtra',
    externalLegacyCode: '',
    areaLevelId: 'ARLVL-0002',
    parentAreaId: 'AREA-0001',
    hierarchyPath: 'India > Maharashtra',
    usageTags: ['Geographic', 'Reporting'],
    areaCategory: '',
    areaClassification: '',
    postalCode: '',
    latitude: null,
    longitude: null,
    geoBoundaryType: 'Not Applicable',
    radiusValue: null,
    radiusUnit: '',
    polygonReference: '',
    mapProvider: '',
    externalBoundaryId: '',
    aliases: [],
    status: 'Active',
    description: '',
    remarks: '',
    createdAt: '2025-01-01T00:00:00.000Z',
    updatedAt: '2025-01-01T00:00:00.000Z',
  },
  {
    id: 'AREA-0003',
    areaCode: 'AREA-0003',
    areaName: 'Pune',
    displayName: 'Pune',
    externalLegacyCode: '',
    areaLevelId: 'ARLVL-0003',
    parentAreaId: 'AREA-0002',
    hierarchyPath: 'India > Maharashtra > Pune',
    usageTags: ['Geographic', 'Sales', 'Service', 'Delivery', 'Reporting'],
    areaCategory: 'Tier 1',
    areaClassification: 'High Potential',
    postalCode: '',
    latitude: null,
    longitude: null,
    geoBoundaryType: 'Not Applicable',
    radiusValue: null,
    radiusUnit: '',
    polygonReference: '',
    mapProvider: '',
    externalBoundaryId: '',
    aliases: [
      {
        id: 'alias-pune-001',
        aliasName: 'Poona',
        aliasType: 'Old Name',
        languageLocale: 'en-IN',
        isSearchable: true,
        status: 'Active',
      },
    ],
    status: 'Active',
    description: '',
    remarks: '',
    createdAt: '2025-01-01T00:00:00.000Z',
    updatedAt: '2025-01-01T00:00:00.000Z',
  },
  {
    id: 'AREA-0004',
    areaCode: 'AREA-0004',
    areaName: 'Hinjewadi',
    displayName: 'Hinjewadi',
    externalLegacyCode: 'PUNE-HINJ',
    areaLevelId: 'ARLVL-0004',
    parentAreaId: 'AREA-0003',
    hierarchyPath: 'India > Maharashtra > Pune > Hinjewadi',
    usageTags: ['Sales', 'Service', 'Delivery', 'Collection'],
    areaCategory: 'Industrial',
    areaClassification: 'Priority Market',
    postalCode: '411057',
    latitude: 18.5913,
    longitude: 73.7389,
    geoBoundaryType: 'Postal / Pin Code Based',
    radiusValue: null,
    radiusUnit: '',
    polygonReference: '',
    mapProvider: '',
    externalBoundaryId: '',
    aliases: [],
    status: 'Active',
    description: '',
    remarks: '',
    createdAt: '2025-01-01T00:00:00.000Z',
    updatedAt: '2025-01-01T00:00:00.000Z',
  },
];
