// ─── UOM Master — Constants ───────────────────────────────────────────────────

import type { UnitType, UomRecord, UomStatus } from '../types/uomMaster.types';

// ─── Lookups ──────────────────────────────────────────────────────────────────

export const UNIT_TYPES: UnitType[] = [
  'Quantity',
  'Volume',
  'Weight',
  'Length',
  'Area',
  'Time',
  'Distance',
  'Packaging',
  'Service',
  'Usage / Meter Reading',
];

export const ROUNDING_RULES: string[] = [
  'Round Up',
  'Round Down',
  'Round Half Up',
  'Round Half Down',
  'No Rounding',
];

export const UOM_STATUSES: UomStatus[] = ['Draft', 'Active', 'Inactive'];

// ─── Unit-type badge colours ──────────────────────────────────────────────────

export const UNIT_TYPE_META: Record<UnitType, { color: string; bgColor: string }> = {
  'Quantity':             { color: '#1D4ED8', bgColor: '#EFF6FF' },
  'Volume':               { color: '#0D9488', bgColor: '#F0FDFA' },
  'Weight':               { color: '#C2410C', bgColor: '#FFF7ED' },
  'Length':               { color: '#7C3AED', bgColor: '#F5F3FF' },
  'Area':                 { color: '#4338CA', bgColor: '#EEF2FF' },
  'Time':                 { color: '#B45309', bgColor: '#FFFBEB' },
  'Distance':             { color: '#15803D', bgColor: '#F0FDF4' },
  'Packaging':            { color: '#9333EA', bgColor: '#FAF5FF' },
  'Service':              { color: '#BE185D', bgColor: '#FDF2F8' },
  'Usage / Meter Reading':{ color: '#0369A1', bgColor: '#F0F9FF' },
};

// ─── Decimal precision range ──────────────────────────────────────────────────

export const DECIMAL_PRECISION_OPTIONS: number[] = [0, 1, 2, 3, 4, 5, 6];

// ─── Default form shell ───────────────────────────────────────────────────────

export const DEFAULT_UOM_FORM: Omit<UomRecord, 'id'> = {
  unitCode:             '',
  unitName:             '',
  unitSymbol:           '',
  unitType:             '',
  description:          '',
  allowDecimal:         false,
  qtyDecimalPrecision:  null,
  roundingRule:         '',
  status:               'Draft',
  effectiveFromDate:    '',
  effectiveToDate:      '',
  conversions:          [],
};

// ─── Sequence counter (in-memory; replace with backend call) ─────────────────
let _seqCounter = 12;

export function generateUomCode(): string {
  _seqCounter += 1;
  return `UOM-${String(_seqCounter).padStart(4, '0')}`;
}

// ─── Mock seed data ───────────────────────────────────────────────────────────

export const MOCK_UOMS: UomRecord[] = [
  {
    id: 'uom-001',
    unitCode: 'UOM-0001',
    unitName: 'Kilogram',
    unitSymbol: 'KG',
    unitType: 'Weight',
    description: 'Standard unit of mass in the metric system.',
    allowDecimal: true,
    qtyDecimalPrecision: 3,
    roundingRule: 'Round Half Up',
    status: 'Active',
    effectiveFromDate: '01/01/2024',
    effectiveToDate: '',
    conversions: [
      {
        id: 'c-001-g',
        fromUnitCode: 'UOM-0001',
        fromUnitName: 'Kilogram',
        toUnitCode: 'UOM-0002',
        toUnitName: 'Gram',
        conversionFactor: 1000,
        decimalPrecision: 0,
        roundingRule: 'No Rounding',
        isAutoReverse: false,
        status: 'Active',
      },
    ],
  },
  {
    id: 'uom-002',
    unitCode: 'UOM-0002',
    unitName: 'Gram',
    unitSymbol: 'G',
    unitType: 'Weight',
    description: 'One-thousandth of a kilogram.',
    allowDecimal: false,
    qtyDecimalPrecision: null,
    roundingRule: '',
    status: 'Active',
    effectiveFromDate: '01/01/2024',
    effectiveToDate: '',
    conversions: [
      {
        id: 'c-002-kg',
        fromUnitCode: 'UOM-0002',
        fromUnitName: 'Gram',
        toUnitCode: 'UOM-0001',
        toUnitName: 'Kilogram',
        conversionFactor: 0.001,
        decimalPrecision: 3,
        roundingRule: 'Round Half Up',
        isAutoReverse: true,
        status: 'Active',
      },
    ],
  },
  {
    id: 'uom-003',
    unitCode: 'UOM-0003',
    unitName: 'Litre',
    unitSymbol: 'LTR',
    unitType: 'Volume',
    description: 'Standard metric unit of volume.',
    allowDecimal: true,
    qtyDecimalPrecision: 2,
    roundingRule: 'Round Half Up',
    status: 'Active',
    effectiveFromDate: '01/01/2024',
    effectiveToDate: '',
    conversions: [
      {
        id: 'c-003-ml',
        fromUnitCode: 'UOM-0003',
        fromUnitName: 'Litre',
        toUnitCode: 'UOM-0004',
        toUnitName: 'Millilitre',
        conversionFactor: 1000,
        decimalPrecision: 0,
        roundingRule: 'No Rounding',
        isAutoReverse: false,
        status: 'Active',
      },
    ],
  },
  {
    id: 'uom-004',
    unitCode: 'UOM-0004',
    unitName: 'Millilitre',
    unitSymbol: 'ML',
    unitType: 'Volume',
    description: 'One-thousandth of a litre.',
    allowDecimal: false,
    qtyDecimalPrecision: null,
    roundingRule: '',
    status: 'Active',
    effectiveFromDate: '01/01/2024',
    effectiveToDate: '',
    conversions: [],
  },
  {
    id: 'uom-005',
    unitCode: 'UOM-0005',
    unitName: 'Piece',
    unitSymbol: 'PCS',
    unitType: 'Quantity',
    description: 'Individual countable unit.',
    allowDecimal: false,
    qtyDecimalPrecision: null,
    roundingRule: 'Round Up',
    status: 'Active',
    effectiveFromDate: '01/01/2024',
    effectiveToDate: '',
    conversions: [],
  },
  {
    id: 'uom-006',
    unitCode: 'UOM-0006',
    unitName: 'Dozen',
    unitSymbol: 'DOZ',
    unitType: 'Quantity',
    description: 'A group of twelve units.',
    allowDecimal: false,
    qtyDecimalPrecision: null,
    roundingRule: '',
    status: 'Active',
    effectiveFromDate: '01/01/2024',
    effectiveToDate: '',
    conversions: [
      {
        id: 'c-006-pcs',
        fromUnitCode: 'UOM-0006',
        fromUnitName: 'Dozen',
        toUnitCode: 'UOM-0005',
        toUnitName: 'Piece',
        conversionFactor: 12,
        decimalPrecision: 0,
        roundingRule: 'No Rounding',
        isAutoReverse: false,
        status: 'Active',
      },
    ],
  },
  {
    id: 'uom-007',
    unitCode: 'UOM-0007',
    unitName: 'Metre',
    unitSymbol: 'M',
    unitType: 'Length',
    description: 'Standard SI unit of length.',
    allowDecimal: true,
    qtyDecimalPrecision: 2,
    roundingRule: 'Round Half Up',
    status: 'Active',
    effectiveFromDate: '01/01/2024',
    effectiveToDate: '',
    conversions: [
      {
        id: 'c-007-cm',
        fromUnitCode: 'UOM-0007',
        fromUnitName: 'Metre',
        toUnitCode: 'UOM-0008',
        toUnitName: 'Centimetre',
        conversionFactor: 100,
        decimalPrecision: 0,
        roundingRule: 'No Rounding',
        isAutoReverse: false,
        status: 'Active',
      },
    ],
  },
  {
    id: 'uom-008',
    unitCode: 'UOM-0008',
    unitName: 'Centimetre',
    unitSymbol: 'CM',
    unitType: 'Length',
    description: 'One-hundredth of a metre.',
    allowDecimal: true,
    qtyDecimalPrecision: 1,
    roundingRule: '',
    status: 'Active',
    effectiveFromDate: '01/01/2024',
    effectiveToDate: '',
    conversions: [],
  },
  {
    id: 'uom-009',
    unitCode: 'UOM-0009',
    unitName: 'Box',
    unitSymbol: 'BOX',
    unitType: 'Packaging',
    description: 'Standard packaging box unit.',
    allowDecimal: false,
    qtyDecimalPrecision: null,
    roundingRule: 'Round Up',
    status: 'Active',
    effectiveFromDate: '01/01/2024',
    effectiveToDate: '',
    conversions: [],
  },
  {
    id: 'uom-010',
    unitCode: 'UOM-0010',
    unitName: 'Hour',
    unitSymbol: 'HR',
    unitType: 'Time',
    description: 'Unit of time — 60 minutes.',
    allowDecimal: true,
    qtyDecimalPrecision: 2,
    roundingRule: 'Round Half Up',
    status: 'Inactive',
    effectiveFromDate: '01/01/2024',
    effectiveToDate: '31/12/2024',
    conversions: [],
  },
  {
    id: 'uom-011',
    unitCode: 'UOM-0011',
    unitName: 'Square Metre',
    unitSymbol: 'SQM',
    unitType: 'Area',
    description: 'Standard metric area unit.',
    allowDecimal: true,
    qtyDecimalPrecision: 2,
    roundingRule: 'Round Half Up',
    status: 'Active',
    effectiveFromDate: '01/01/2024',
    effectiveToDate: '',
    conversions: [],
  },
  {
    id: 'uom-012',
    unitCode: 'UOM-0012',
    unitName: 'Kilometre',
    unitSymbol: 'KM',
    unitType: 'Distance',
    description: 'One thousand metres.',
    allowDecimal: true,
    qtyDecimalPrecision: 3,
    roundingRule: 'Round Half Up',
    status: 'Active',
    effectiveFromDate: '01/01/2024',
    effectiveToDate: '',
    conversions: [],
  },
  {
    id: 'uom-013',
    unitCode: 'UOM-0013',
    unitName: 'Tonne',
    unitSymbol: 'TON',
    unitType: 'Weight',
    description: 'Metric tonne — 1000 kilograms. (Draft — pending review)',
    allowDecimal: true,
    qtyDecimalPrecision: 3,
    roundingRule: 'Round Half Up',
    status: 'Draft',
    effectiveFromDate: '',
    effectiveToDate: '',
    conversions: [],
  },
  {
    id: 'uom-014',
    unitCode: 'UOM-0014',
    unitName: 'Carton',
    unitSymbol: 'CTN',
    unitType: 'Packaging',
    description: 'Standard shipping carton. (Draft — pending approval)',
    allowDecimal: false,
    qtyDecimalPrecision: null,
    roundingRule: 'Round Up',
    status: 'Draft',
    effectiveFromDate: '',
    effectiveToDate: '',
    conversions: [],
  },
];
