import { roundToTwo } from '../../utils/round.js';

function amount(value: number): string {
  return roundToTwo(value).toFixed(2);
}

type SerializableRecord = { toJSON?: () => Record<string, unknown> } & Record<string, unknown>;

export function mapReceipt(document: SerializableRecord) {
  const source = document.toJSON ? document.toJSON() : document;
  const lines = (source.lines as Array<Record<string, unknown>>) ?? [];

  return {
    id: source.id,
    number: source.number,
    orderDateTime: source.orderDateTime,
    purchaseOrderNumber: source.purchaseOrderNumber,
    requisitionNumber: source.requisitionNumber,
    requisitionDate: source.requisitionDate,
    supplierName: source.supplierName,
    buyerName: source.buyerName,
    createdBy: source.createdBy,
    createdOn: source.createdOn,
    buyerEmail: source.buyerEmail,
    branch: source.branch,
    department: source.department,
    priority: source.priority,
    status: source.status,
    lifecycleStatus: source.lifecycleStatus,
    expectedDeliveryDate: source.expectedDeliveryDate,
    paymentMode: source.paymentMode,
    paymentTerm: source.paymentTerm,
    placeOfSupply: source.placeOfSupply,
    receivingLocation: source.receivingLocation,
    receiveDate: source.receiveDate,
    receivedBy: source.receivedBy,
    supplierInvoiceNumber: source.supplierInvoiceNumber,
    supplierInvoiceDate: source.supplierInvoiceDate,
    transporterName: source.transportDetails?.transporterName ?? '',
    vehicleNumber: source.transportDetails?.vehicleNumber ?? '',
    consignmentNumber: source.transportDetails?.consignmentNumber ?? '',
    consignmentDate: source.transportDetails?.consignmentDate ?? '',
    insuranceProvider: source.insuranceDetails?.insuranceProvider ?? '',
    insuranceContactPerson: source.insuranceDetails?.insuranceContactPerson ?? '',
    insuranceType: source.insuranceDetails?.insuranceType ?? '',
    insuranceNumber: source.insuranceDetails?.insuranceNumber ?? '',
    insuranceAddress: source.insuranceDetails?.insuranceAddress ?? '',
    taxableAmount: amount(source.taxableAmount),
    totalDiscount: amount(source.totalDiscount),
    totalTaxes: amount(source.totalTaxes),
    totalAmount: amount(source.totalAmount),
    currency: source.currency,
    notes: source.notes,
    lines: lines.map((line) => ({
      id: typeof line.id === 'string' ? line.id : String(line._id ?? ''),
      lineNumber: line.lineNumber,
      sourceOrderLineId: line.sourceOrderLineId,
      itemCode: line.itemCode,
      itemName: line.itemName,
      description: line.description,
      hsnSac: line.hsnSac,
      uom: line.uom,
      priority: line.priority,
      purchaseRate: amount(Number(line.purchaseRate ?? 0)),
      orderedQty: amount(Number(line.orderedQty ?? 0)),
      previouslyReceivedQty: amount(Number(line.previouslyReceivedQty ?? 0)),
      supplierInvoiceQty: amount(Number(line.supplierInvoiceQty ?? 0)),
      receivedQty: amount(Number(line.receivedQty ?? 0)),
      shortageQty: amount(Number(line.shortageQty ?? 0)),
      excessQty: amount(Number(line.excessQty ?? 0)),
      damageQty: amount(Number(line.damageQty ?? 0)),
      damageReason: line.damageReason,
      batchNo: line.batchNo,
      serialNo: line.serialNo,
      manufacturingDate: line.manufacturingDate,
      storageLocation: line.storageLocation,
      boxCount: amount(Number(line.boxCount ?? 0)),
      remarks: line.remarks,
      discountPercent: amount(Number(line.discountPercent ?? 0)),
      discountAmount: amount(Number(line.discountAmount ?? 0)),
      taxableAmount: amount(Number(line.taxableAmount ?? 0)),
      taxColumns: line.taxColumns,
      totalAmount: amount(Number(line.totalAmount ?? 0)),
      quantity: amount(Number(line.receivedQty ?? 0)),
      unitPrice: amount(Number(line.purchaseRate ?? 0)),
      expectedDate: line.manufacturingDate,
      amount: amount(Number(line.totalAmount ?? 0)),
    })),
  };
}
