import { z } from 'zod';
import { APPROVAL_STATUS_VALUES, PAYMENT_MODE_VALUES, PRIORITY_VALUES } from '../../constants/domain.js';

const lineSchema = z.object({
  id: z.string().optional(),
  lineNumber: z.number().int().positive().optional(),
  sourceOrderLineId: z.string().optional(),
  itemCode: z.string().trim().min(1),
  itemName: z.string().trim().min(1),
  description: z.string().trim().max(1000).optional().default(''),
  hsnSac: z.string().trim().max(50).optional().default(''),
  uom: z.string().trim().min(1),
  priority: z.enum(PRIORITY_VALUES).optional().default('Medium'),
  purchaseRate: z.coerce.number().min(0).optional().default(0),
  orderedQty: z.coerce.number().min(0).optional().default(0),
  previouslyReceivedQty: z.coerce.number().min(0).optional().default(0),
  supplierInvoiceQty: z.coerce.number().min(0).optional().default(0),
  receivedQty: z.coerce.number().min(0),
  damageQty: z.coerce.number().min(0).optional().default(0),
  damageReason: z.string().trim().max(200).optional().default(''),
  batchNo: z.string().trim().max(100).optional().default(''),
  serialNo: z.string().trim().max(100).optional().default(''),
  manufacturingDate: z.string().datetime().or(z.string().date()).optional(),
  storageLocation: z.string().trim().max(150).optional().default(''),
  boxCount: z.coerce.number().min(0).optional().default(0),
  remarks: z.string().trim().max(500).optional().default(''),
  discountPercent: z.coerce.number().min(0).optional().default(0),
  discountAmount: z.coerce.number().min(0).optional().default(0),
  taxRate: z.coerce.number().min(0).optional().default(0),
  taxColumns: z.string().trim().max(100).optional().default(''),
});

export const receiptBodySchema = z.object({
  number: z.string().trim().optional(),
  sourceOrderId: z.string().optional(),
  sourceRequisitionId: z.string().optional(),
  purchaseOrderNumber: z.string().trim().optional().default(''),
  requisitionNumber: z.string().trim().optional().default(''),
  requisitionDate: z.string().datetime().or(z.string().date()).optional(),
  supplierId: z.string().optional(),
  supplierName: z.string().trim().min(1),
  department: z.string().trim().min(1),
  priority: z.enum(PRIORITY_VALUES),
  status: z.enum(APPROVAL_STATUS_VALUES).optional().default('Draft'),
  placeOfSupply: z.string().trim().max(150).optional().default(''),
  receivingLocation: z.string().trim().max(150).optional().default(''),
  receiveDate: z.string().datetime().or(z.string().date()),
  receivedBy: z.string().trim().max(150).optional().default(''),
  paymentMode: z.enum(PAYMENT_MODE_VALUES).optional(),
  paymentTerm: z.string().trim().max(100).optional().default(''),
  supplierInvoiceNumber: z.string().trim().max(100).optional().default(''),
  supplierInvoiceDate: z.string().datetime().or(z.string().date()).optional(),
  createdBy: z.string().trim().optional().default(''),
  orderDateTime: z.string().datetime().or(z.string().date()).optional(),
  expectedDeliveryDate: z.string().datetime().or(z.string().date()).optional(),
  buyerName: z.string().trim().optional().default(''),
  buyerEmail: z.string().email().optional().or(z.literal('')).default(''),
  branch: z.string().trim().optional().default(''),
  currency: z.string().trim().max(10).optional().default('USD'),
  notes: z.string().trim().max(2000).optional().default(''),
  transporterName: z.string().trim().max(150).optional().default(''),
  vehicleNumber: z.string().trim().max(100).optional().default(''),
  consignmentNumber: z.string().trim().max(100).optional().default(''),
  consignmentDate: z.string().datetime().or(z.string().date()).optional(),
  insuranceProvider: z.string().trim().max(150).optional().default(''),
  insuranceContactPerson: z.string().trim().max(150).optional().default(''),
  insuranceType: z.string().trim().max(150).optional().default(''),
  insuranceNumber: z.string().trim().max(100).optional().default(''),
  insuranceAddress: z.string().trim().max(250).optional().default(''),
  allowOverReceipt: z.boolean().optional().default(false),
  actorName: z.string().trim().optional(),
  actorEmail: z.string().email().optional().or(z.literal('')),
  lines: z.array(lineSchema).min(1),
});

export const receiptUpdateSchema = receiptBodySchema.partial().extend({
  lines: z.array(lineSchema).min(1).optional(),
});

export const receiptListQuerySchema = z.object({
  page: z.string().optional(),
  limit: z.string().optional(),
  search: z.string().optional(),
  sortBy: z
    .enum([
      'createdAt',
      'updatedAt',
      'number',
      'supplierName',
      'department',
      'priority',
      'status',
      'lifecycleStatus',
      'receiveDate',
      'orderDateTime',
      'requisitionDate',
      'totalAmount',
    ])
    .optional(),
  sortOrder: z.enum(['asc', 'desc']).optional(),
  supplier: z.string().optional(),
  priority: z.string().optional(),
  status: z.string().optional(),
  lifecycleStatus: z.string().optional(),
  department: z.string().optional(),
  createdBy: z.string().optional(),
  purchaseOrderNumber: z.string().optional(),
  requisitionNumber: z.string().optional(),
  receiveDateFrom: z.string().optional(),
  receiveDateTo: z.string().optional(),
  poDateFrom: z.string().optional(),
  poDateTo: z.string().optional(),
  prDateFrom: z.string().optional(),
  prDateTo: z.string().optional(),
});

export const documentIdParamsSchema = z.object({
  id: z.string().min(1),
});

export const statusUpdateBodySchema = z.object({
  status: z.enum(APPROVAL_STATUS_VALUES),
  actorName: z.string().trim().optional(),
  actorEmail: z.string().email().optional().or(z.literal('')),
  comment: z.string().trim().max(1000).optional(),
});
